<?php

namespace Database\Seeders;

use App\Models\Committee;
use Illuminate\Database\Seeder;

class CommitteeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Committee::insert([
            [
                'kh_name' => 'គណៈកិត្តិយសកណ្តាល',
                'en_name' => 'Central Honorary Committee',
                'branch_id' => 0,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 1,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តបន្ទាយមានជ័យ',
                'en_name' => 'Banteay Meanchey',
                'branch_id' => 1,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តបាត់ដំបង',
                'en_name' => 'Battambang',
                'branch_id' => 2,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកំពង់ចាម',
                'en_name' => 'Kampong Cham',
                'branch_id' => 3,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកំពង់ឆ្នាំង',
                'en_name' => 'Kampong Chhnang',
                'branch_id' => 4,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកំពង់ស្ពឺ',
                'en_name' => 'Kampong Speu',
                'branch_id' => 5,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកំពង់ធំ',
                'en_name' => 'Kampong Thom',
                'branch_id' => 6,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកំពត',
                'en_name' => 'Kampot',
                'branch_id' => 7,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកណ្ដាល',
                'en_name' => 'Kandal',
                'branch_id' => 8,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកោះកុង',
                'en_name' => 'Koh Kong',
                'branch_id' => 9,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តក្រចេះ',
                'en_name' => 'Kratie',
                'branch_id' => 10,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តមណ្ឌលគិរី',
                'en_name' => 'Mondul Kiri',
                'branch_id' => 11,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តរាជធានីភ្នំពេញ',
                'en_name' => 'Phnom Penh',
                'branch_id' => 12,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តព្រះវិហារ',
                'en_name' => 'Preah Vihear',
                'branch_id' => 13,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តព្រៃវែង',
                'en_name' => 'Prey Veng',
                'branch_id' => 14,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តពោធិ៍សាត់',
                'en_name' => 'Pursat',
                'branch_id' => 15,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តរតនគិរី',
                'en_name' => 'Ratanak Kiri',
                'branch_id' => 16,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តសៀមរាប',
                'en_name' => 'Siemreap',
                'branch_id' => 17,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តព្រះសីហនុ',
                'en_name' => 'Preah Sihanouk',
                'branch_id' => 18,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តស្ទឹងត្រែង',
                'en_name' => 'Stung Treng',
                'branch_id' => 19,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តស្វាយរៀង',
                'en_name' => 'Svay Rieng',
                'branch_id' => 20,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តតាកែវ',
                'en_name' => 'Takeo',
                'branch_id' => 21,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តឧត្ដរមានជ័យ',
                'en_name' => 'Oddar Meanchey',
                'branch_id' => 22,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តកែប',
                'en_name' => 'Kep',
                'branch_id' => 23,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តប៉ៃលិន',
                'en_name' => 'Pailin',
                'branch_id' => 24,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                'kh_name' => 'គណ:កិត្តិយសសាខា ខេត្តត្បូងឃ្មុំ',
                'en_name' => 'Tboung Khmum',
                'branch_id' => 25,
                'sub_branch_id' => null,
                'committee_type_id' => 1,
                'committee_level_id' => 2,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមង្គលបូរី",
                "en_name" => "Mongkol Borei",
                "branch_id" => 1,
                "sub_branch_id" => 102,
                'committee_type_id' => 1,
                'committee_level_id' => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកភ្នំស្រុក",
                "en_name" => "Phnum Srok",
                "branch_id" => 1,
                "sub_branch_id" => 103,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រះនេត្រព្រះ",
                "en_name" => "Preah Netr Preah",
                "branch_id" => 1,
                "sub_branch_id" => 104,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអូរជ្រៅ",
                "en_name" => "Ou Chrov",
                "branch_id" => 1,
                "sub_branch_id" => 105,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសិរីសោភ័ណ",
                "en_name" => "Serei Saophoan",
                "branch_id" => 1,
                "sub_branch_id" => 106,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកថ្មពួក",
                "en_name" => "Thma Puok",
                "branch_id" => 1,
                "sub_branch_id" => 107,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្វាយចេក",
                "en_name" => "Svay Chek",
                "branch_id" => 1,
                "sub_branch_id" => 108,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកម៉ាឡៃ",
                "en_name" => "Malai",
                "branch_id" => 1,
                "sub_branch_id" => 109,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកប៉ោយប៉ែត",
                "en_name" => "Paoy Paet",
                "branch_id" => 1,
                "sub_branch_id" => 110,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាណន់",
                "en_name" => "Banan",
                "branch_id" => 2,
                "sub_branch_id" => 201,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកថ្មគោល",
                "en_name" => "Thma Koul",
                "branch_id" => 2,
                "sub_branch_id" => 202,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាត់ដំបង",
                "en_name" => "Battambang",
                "branch_id" => 2,
                "sub_branch_id" => 203,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបវេល",
                "en_name" => "Bavel",
                "branch_id" => 2,
                "sub_branch_id" => 204,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឯកភ្នំ",
                "en_name" => "Aek Phnum",
                "branch_id" => 2,
                "sub_branch_id" => 205,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមោងឫស្សី",
                "en_name" => "Moung Ruessei",
                "branch_id" => 2,
                "sub_branch_id" => 206,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុករតនមណ្ឌល",
                "en_name" => "Rotonak Mondol",
                "branch_id" => 2,
                "sub_branch_id" => 207,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសង្កែ",
                "en_name" => "Sangkae",
                "branch_id" => 2,
                "sub_branch_id" => 208,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសំឡូត",
                "en_name" => "Samlout",
                "branch_id" => 2,
                "sub_branch_id" => 209,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសំពៅលូន",
                "en_name" => "Sampov Lun",
                "branch_id" => 2,
                "sub_branch_id" => 210,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកភ្នំព្រឹក",
                "en_name" => "Phnum Proek",
                "branch_id" => 2,
                "sub_branch_id" => 211,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំរៀង",
                "en_name" => "Kamrieng",
                "branch_id" => 2,
                "sub_branch_id" => 212,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកគាស់ក្រឡ",
                "en_name" => "Koas Krala",
                "branch_id" => 2,
                "sub_branch_id" => 213,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុករុក្ខគិរី",
                "en_name" => "Rukh Kiri",
                "branch_id" => 2,
                "sub_branch_id" => 214,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាធាយ",
                "en_name" => "Batheay",
                "branch_id" => 3,
                "sub_branch_id" => 301,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកចំការលើ",
                "en_name" => "Chamkar Leu",
                "branch_id" => 3,
                "sub_branch_id" => 302,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជើងព្រៃ",
                "en_name" => "Cheung Prey",
                "branch_id" => 3,
                "sub_branch_id" => 303,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់ចាម",
                "en_name" => "Kampong Cham",
                "branch_id" => 3,
                "sub_branch_id" => 305,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់សៀម",
                "en_name" => "Kampong Siem",
                "branch_id" => 3,
                "sub_branch_id" => 306,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកងមាស",
                "en_name" => "Kang Meas",
                "branch_id" => 3,
                "sub_branch_id" => 307,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកោះសូទិន",
                "en_name" => "Kaoh Soutin",
                "branch_id" => 3,
                "sub_branch_id" => 308,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រៃឈរ",
                "en_name" => "Prey Chhor",
                "branch_id" => 3,
                "sub_branch_id" => 313,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្រីសន្ធរ",
                "en_name" => "Srei Santhor",
                "branch_id" => 3,
                "sub_branch_id" => 314,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្ទឹងត្រង់",
                "en_name" => "Stueng Trang",
                "branch_id" => 3,
                "sub_branch_id" => 315,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបរិបូណ៌",
                "en_name" => "Baribour",
                "branch_id" => 4,
                "sub_branch_id" => 401,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជលគីរី",
                "en_name" => "Chol Kiri",
                "branch_id" => 4,
                "sub_branch_id" => 402,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់ឆ្នាំង",
                "en_name" => "Kampong Chhnang",
                "branch_id" => 4,
                "sub_branch_id" => 403,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់លែង",
                "en_name" => "Kampong Leaeng",
                "branch_id" => 4,
                "sub_branch_id" => 404,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់ត្រឡាច",
                "en_name" => "Kampong Tralach",
                "branch_id" => 4,
                "sub_branch_id" => 405,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុករលាប្អៀរ",
                "en_name" => "Rolea Bier",
                "branch_id" => 4,
                "sub_branch_id" => 406,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសាមគ្គីមានជ័យ",
                "en_name" => "Sameakki Mean Chey",
                "branch_id" => 4,
                "sub_branch_id" => 407,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកទឹកផុស",
                "en_name" => "Tuek Phos",
                "branch_id" => 4,
                "sub_branch_id" => 408,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបរសេដ្ឋ",
                "en_name" => "Basedth",
                "branch_id" => 5,
                "sub_branch_id" => 501,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកច្បារមន",
                "en_name" => "Chbar Mon",
                "branch_id" => 5,
                "sub_branch_id" => 502,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកគងពិសី",
                "en_name" => "Kong Pisei",
                "branch_id" => 5,
                "sub_branch_id" => 503,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឱរ៉ាល់",
                "en_name" => "Aoral",
                "branch_id" => 5,
                "sub_branch_id" => 504,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឧដុង្គ",
                "en_name" => "Odongk",
                "branch_id" => 5,
                "sub_branch_id" => 505,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកភ្នំស្រួច",
                "en_name" => "Phnum Sruoch",
                "branch_id" => 5,
                "sub_branch_id" => 506,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសំរោងទង",
                "en_name" => "Samraong Tong",
                "branch_id" => 5,
                "sub_branch_id" => 507,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកថ្ពង",
                "en_name" => "Thpong",
                "branch_id" => 5,
                "sub_branch_id" => 508,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបារាយណ៍",
                "en_name" => "Baray",
                "branch_id" => 6,
                "sub_branch_id" => 601,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់ស្វាយ",
                "en_name" => "Kampong Svay",
                "branch_id" => 6,
                "sub_branch_id" => 602,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្ទឹងសែន",
                "en_name" => "Stueng Saen",
                "branch_id" => 6,
                "sub_branch_id" => 603,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកប្រាសាទបល្ល័ង្គ",
                "en_name" => "Prasat Ballangk",
                "branch_id" => 6,
                "sub_branch_id" => 604,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកប្រាសាទសំបូរ",
                "en_name" => "Prasat Sambour",
                "branch_id" => 6,
                "sub_branch_id" => 605,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសន្តាន់",
                "en_name" => "Sandan",
                "branch_id" => 6,
                "sub_branch_id" => 606,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសន្ទុក",
                "en_name" => "Santuk",
                "branch_id" => 6,
                "sub_branch_id" => 607,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្ទោង",
                "en_name" => "Stoung",
                "branch_id" => 6,
                "sub_branch_id" => 608,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកតាំងគោក",
                "en_name" => "Taing Kouk",
                "branch_id" => 6,
                "sub_branch_id" => 609,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអង្គរជ័យ",
                "en_name" => "Angkor Chey",
                "branch_id" => 7,
                "sub_branch_id" => 701,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបន្ទាយមាស",
                "en_name" => "Banteay Meas",
                "branch_id" => 7,
                "sub_branch_id" => 702,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឈូក",
                "en_name" => "Chhuk",
                "branch_id" => 7,
                "sub_branch_id" => 703,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជុំគិរី",
                "en_name" => "Chum Kiri",
                "branch_id" => 7,
                "sub_branch_id" => 704,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកដងទង់",
                "en_name" => "Dang Tong",
                "branch_id" => 7,
                "sub_branch_id" => 705,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់ត្រាច",
                "en_name" => "Kampong Trach",
                "branch_id" => 7,
                "sub_branch_id" => 706,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកទឹកឈូ",
                "en_name" => "Tuek Chhou",
                "branch_id" => 7,
                "sub_branch_id" => 707,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពត",
                "en_name" => "Kampot",
                "branch_id" => 7,
                "sub_branch_id" => 708,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកណ្ដាលស្ទឹង",
                "en_name" => "Kandal Stueng",
                "branch_id" => 8,
                "sub_branch_id" => 801,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកៀនស្វាយ",
                "en_name" => "Kien Svay",
                "branch_id" => 8,
                "sub_branch_id" => 802,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកខ្សាច់កណ្ដាល",
                "en_name" => "Khsach Kandal",
                "branch_id" => 8,
                "sub_branch_id" => 803,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកោះធំ",
                "en_name" => "Kaoh Thum",
                "branch_id" => 8,
                "sub_branch_id" => 804,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកលើកដែក",
                "en_name" => "Leuk Daek",
                "branch_id" => 8,
                "sub_branch_id" => 805,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកល្វាឯម",
                "en_name" => "Lvea Aem",
                "branch_id" => 8,
                "sub_branch_id" => 806,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមុខកំពូល",
                "en_name" => "Mukh Kampul",
                "branch_id" => 8,
                "sub_branch_id" => 807,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអង្គស្នួល",
                "en_name" => "Angk Snuol",
                "branch_id" => 8,
                "sub_branch_id" => 808,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពញាឮ",
                "en_name" => "Ponhea Lueu",
                "branch_id" => 8,
                "sub_branch_id" => 809,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្អាង",
                "en_name" => "Sang",
                "branch_id" => 8,
                "sub_branch_id" => 810,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកតាខ្មៅ",
                "en_name" => "Ta Khmau",
                "branch_id" => 8,
                "sub_branch_id" => 811,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបុទុមសាគរ",
                "en_name" => "Botum Sakor",
                "branch_id" => 9,
                "sub_branch_id" => 901,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកគិរីសាគរ",
                "en_name" => "Kiri Sakor",
                "branch_id" => 9,
                "sub_branch_id" => 902,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកោះកុង",
                "en_name" => "Kaoh Kong",
                "branch_id" => 9,
                "sub_branch_id" => 903,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកខេមរភូមិន្ទ",
                "en_name" => "Khemara Phoumin",
                "branch_id" => 9,
                "sub_branch_id" => 904,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមណ្ឌលសីមា",
                "en_name" => "Mondol Seima",
                "branch_id" => 9,
                "sub_branch_id" => 905,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្រែ អំបិល",
                "en_name" => "Srae Ambel",
                "branch_id" => 9,
                "sub_branch_id" => 906,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកថ្មបាំង",
                "en_name" => "Thma Bang",
                "branch_id" => 9,
                "sub_branch_id" => 907,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឆ្លូង",
                "en_name" => "Chhloung",
                "branch_id" => 10,
                "sub_branch_id" => 1001,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកក្រចេះ",
                "en_name" => "Kracheh",
                "branch_id" => 10,
                "sub_branch_id" => 1002,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រែកប្រសព្វ",
                "en_name" => "Prek Prasab",
                "branch_id" => 10,
                "sub_branch_id" => 1003,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសំបូរ",
                "en_name" => "Sambour",
                "branch_id" => 10,
                "sub_branch_id" => 1004,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្នួល",
                "en_name" => "Snuol",
                "branch_id" => 10,
                "sub_branch_id" => 1005,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកចិត្របុរី",
                "en_name" => "Chetr Borei",
                "branch_id" => 10,
                "sub_branch_id" => 1006,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកែវសីមា",
                "en_name" => "Kaev Seima",
                "branch_id" => 11,
                "sub_branch_id" => 1101,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកោះញែក",
                "en_name" => "Kaoh Nheaek",
                "branch_id" => 11,
                "sub_branch_id" => 1102,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអូររាំង",
                "en_name" => "Ou Reang",
                "branch_id" => 11,
                "sub_branch_id" => 1103,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពេជ្រាដា",
                "en_name" => "Pech Chreada",
                "branch_id" => 11,
                "sub_branch_id" => 1104,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសែនមនោរម្យ",
                "en_name" => "Saen Monourom",
                "branch_id" => 11,
                "sub_branch_id" => 1105,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកចំការមន",
                "en_name" => "Chamkar Mon",
                "branch_id" => 12,
                "sub_branch_id" => 1201,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកដូនពេញ",
                "en_name" => "Doun Penh",
                "branch_id" => 12,
                "sub_branch_id" => 1202,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុក៧មករា",
                "en_name" => "Prampir Meakkakra",
                "branch_id" => 12,
                "sub_branch_id" => 1203,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកទួលគោក",
                "en_name" => "Tuol Kouk",
                "branch_id" => 12,
                "sub_branch_id" => 1204,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកដង្កោ",
                "en_name" => "Dangkao",
                "branch_id" => 12,
                "sub_branch_id" => 1205,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមានជ័យ",
                "en_name" => "Mean Chey",
                "branch_id" => 12,
                "sub_branch_id" => 1206,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឫស្សីកែវ",
                "en_name" => "Russey Keo",
                "branch_id" => 12,
                "sub_branch_id" => 1207,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសែនសុខ",
                "en_name" => "Saensokh",
                "branch_id" => 12,
                "sub_branch_id" => 1208,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពោធិ៍សែនជ័យ",
                "en_name" => "Pur SenChey",
                "branch_id" => 12,
                "sub_branch_id" => 1209,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជ្រោយចង្វារ",
                "en_name" => "Chraoy Chongvar",
                "branch_id" => 12,
                "sub_branch_id" => 1210,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រែកព្នៅ",
                "en_name" => "Praek Pnov",
                "branch_id" => 12,
                "sub_branch_id" => 1211,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកច្បារអំពៅ",
                "en_name" => "Chbar Ampov",
                "branch_id" => 12,
                "sub_branch_id" => 1212,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបឹងកេងកង",
                "en_name" => "Kengkong",
                "branch_id" => 12,
                "sub_branch_id" => 1213,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំបូល",
                "en_name" => "Kambol",
                "branch_id" => 12,
                "sub_branch_id" => 1214,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជ័យសែន",
                "en_name" => "Chey Saen",
                "branch_id" => 13,
                "sub_branch_id" => 1301,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកឆែប",
                "en_name" => "Chhaeb",
                "branch_id" => 13,
                "sub_branch_id" => 1302,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជាំក្សាន្ដ",
                "en_name" => "Choam Ksant",
                "branch_id" => 13,
                "sub_branch_id" => 1303,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកគូលែន",
                "en_name" => "Kuleaen",
                "branch_id" => 13,
                "sub_branch_id" => 1304,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុករវៀង",
                "en_name" => "Rovieng",
                "branch_id" => 13,
                "sub_branch_id" => 1305,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសង្គមថ្មី",
                "en_name" => "Sangkum Thmei",
                "branch_id" => 13,
                "sub_branch_id" => 1306,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកត្បែងមានជ័យ",
                "en_name" => "Tbaeng Mean Chey",
                "branch_id" => 13,
                "sub_branch_id" => 1307,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រះវិហារ",
                "en_name" => "Preah Vihear",
                "branch_id" => 13,
                "sub_branch_id" => 1308,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាភ្នំ",
                "en_name" => "Ba Phnum",
                "branch_id" => 14,
                "sub_branch_id" => 1401,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំចាយមារ",
                "en_name" => "Kamchay Mear",
                "branch_id" => 14,
                "sub_branch_id" => 1402,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់ត្របែក",
                "en_name" => "Kampong Trabaek",
                "branch_id" => 14,
                "sub_branch_id" => 1403,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកញ្ជ្រៀច",
                "en_name" => "Kanhchriech",
                "branch_id" => 14,
                "sub_branch_id" => 1404,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមេសាង",
                "en_name" => "Me Sang",
                "branch_id" => 14,
                "sub_branch_id" => 1405,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពាមជរ",
                "en_name" => "Peam Chor",
                "branch_id" => 14,
                "sub_branch_id" => 1406,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពាមរក៍",
                "en_name" => "Peam Ro",
                "branch_id" => 14,
                "sub_branch_id" => 1407,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពារាំង",
                "en_name" => "Pea Reang",
                "branch_id" => 14,
                "sub_branch_id" => 1408,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រះស្ដេច",
                "en_name" => "Preah Sdach",
                "branch_id" => 14,
                "sub_branch_id" => 1409,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រៃវែង",
                "en_name" => "Prey Veng",
                "branch_id" => 14,
                "sub_branch_id" => 1410,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពោធិ៍រៀង",
                "en_name" => "Pur Rieng",
                "branch_id" => 14,
                "sub_branch_id" => 1411,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស៊ីធរកណ្ដាល",
                "en_name" => "Sithor Kandal",
                "branch_id" => 14,
                "sub_branch_id" => 1412,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្វាយអន្ទរ",
                "en_name" => "Svay Antor",
                "branch_id" => 14,
                "sub_branch_id" => 1413,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាកាន",
                "en_name" => "Bakan",
                "branch_id" => 15,
                "sub_branch_id" => 1501,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកណ្ដៀង",
                "en_name" => "Kandieng",
                "branch_id" => 15,
                "sub_branch_id" => 1502,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកក្រគរ",
                "en_name" => "Krakor",
                "branch_id" => 15,
                "sub_branch_id" => 1503,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកភ្នំក្រវ៉ាញ",
                "en_name" => "Phnum Kravanh",
                "branch_id" => 15,
                "sub_branch_id" => 1504,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពោធិ៍សាត់",
                "en_name" => "Pursat",
                "branch_id" => 15,
                "sub_branch_id" => 1505,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកវាលវែង",
                "en_name" => "Veal Veaeng",
                "branch_id" => 15,
                "sub_branch_id" => 1506,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកតាលោសែនជ័យ",
                "en_name" => "Ta Lou Senchey",
                "branch_id" => 15,
                "sub_branch_id" => 1507,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអណ្ដូងមាស",
                "en_name" => "Andoung Meas",
                "branch_id" => 16,
                "sub_branch_id" => 1601,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបានលុង",
                "en_name" => "Ban Lung",
                "branch_id" => 16,
                "sub_branch_id" => 1602,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបរកែវ",
                "en_name" => "Bar Kaev",
                "branch_id" => 16,
                "sub_branch_id" => 1603,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកូនមុំ",
                "en_name" => "Koun Mom",
                "branch_id" => 16,
                "sub_branch_id" => 1604,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកលំផាត់",
                "en_name" => "Lumphat",
                "branch_id" => 16,
                "sub_branch_id" => 1605,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអូរជុំ",
                "en_name" => "Ou Chum",
                "branch_id" => 16,
                "sub_branch_id" => 1606,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអូរយ៉ាដាវ",
                "en_name" => "Ou Ya Dav",
                "branch_id" => 16,
                "sub_branch_id" => 1607,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកតាវែង",
                "en_name" => "Ta Veaeng",
                "branch_id" => 16,
                "sub_branch_id" => 1608,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកវើនសៃ",
                "en_name" => "Veun Sai",
                "branch_id" => 16,
                "sub_branch_id" => 1609,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអង្គរជុំ",
                "en_name" => "Angkor Chum",
                "branch_id" => 17,
                "sub_branch_id" => 1701,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអង្គរធំ",
                "en_name" => "Angkor Thum",
                "branch_id" => 17,
                "sub_branch_id" => 1702,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបន្ទាយស្រី",
                "en_name" => "Banteay Srei",
                "branch_id" => 17,
                "sub_branch_id" => 1703,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកជីក្រែង",
                "en_name" => "Chi Kraeng",
                "branch_id" => 17,
                "sub_branch_id" => 1704,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកក្រឡាញ់",
                "en_name" => "Kralanh",
                "branch_id" => 17,
                "sub_branch_id" => 1706,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពួក",
                "en_name" => "Puok",
                "branch_id" => 17,
                "sub_branch_id" => 1707,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកប្រាសាទបាគង",
                "en_name" => "Prasat Bakong",
                "branch_id" => 17,
                "sub_branch_id" => 1709,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសៀមរាប",
                "en_name" => "Siem Reap",
                "branch_id" => 17,
                "sub_branch_id" => 1710,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសូទ្រនិគម",
                "en_name" => "Soutr Nikom",
                "branch_id" => 17,
                "sub_branch_id" => 1711,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្រីស្នំ",
                "en_name" => "Srei Snam",
                "branch_id" => 17,
                "sub_branch_id" => 1712,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្វាយលើ",
                "en_name" => "Svay Leu",
                "branch_id" => 17,
                "sub_branch_id" => 1713,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកវ៉ារិន",
                "en_name" => "Varin",
                "branch_id" => 17,
                "sub_branch_id" => 1714,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រះសីហនុ",
                "en_name" => "Preah Sihanouk",
                "branch_id" => 18,
                "sub_branch_id" => 1801,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រៃនប់",
                "en_name" => "Prey Nob",
                "branch_id" => 18,
                "sub_branch_id" => 1802,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្ទឹងហាវ",
                "en_name" => "Stueng Hav",
                "branch_id" => 18,
                "sub_branch_id" => 1803,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់សីលា",
                "en_name" => "Kampong Seila",
                "branch_id" => 18,
                "sub_branch_id" => 1804,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកោះរ៉ុង",
                "en_name" => "Kaoh Rung Municipality",
                "branch_id" => 18,
                "sub_branch_id" => 1805,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសេសាន",
                "en_name" => "Sesan",
                "branch_id" => 19,
                "sub_branch_id" => 1901,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសៀមបូក",
                "en_name" => "Siem Bouk",
                "branch_id" => 19,
                "sub_branch_id" => 1902,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសៀមប៉ាង",
                "en_name" => "Siem Pang",
                "branch_id" => 19,
                "sub_branch_id" => 1903,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្ទឹងត្រែង",
                "en_name" => "Stueng Traeng",
                "branch_id" => 19,
                "sub_branch_id" => 1904,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកថាឡាបរិវ៉ាត់",
                "en_name" => "Thala Barivat",
                "branch_id" => 19,
                "sub_branch_id" => 1905,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបុរីអូរស្វាយសែនជ័យ",
                "en_name" => "Borei Ou Svay Senchey",
                "branch_id" => 19,
                "sub_branch_id" => 1906,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកចន្ទ្រា",
                "en_name" => "Chantrea",
                "branch_id" => 20,
                "sub_branch_id" => 2001,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកំពង់រោទិ៍",
                "en_name" => "Kampong Rou",
                "branch_id" => 20,
                "sub_branch_id" => 2002,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុករំដួល",
                "en_name" => "Rumduol",
                "branch_id" => 20,
                "sub_branch_id" => 2003,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុករមាសហែក",
                "en_name" => "Romeas Haek",
                "branch_id" => 20,
                "sub_branch_id" => 2004,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្វាយជ្រំ",
                "en_name" => "Svay Chrum",
                "branch_id" => 20,
                "sub_branch_id" => 2005,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្វាយរៀង",
                "en_name" => "Svay Rieng",
                "branch_id" => 20,
                "sub_branch_id" => 2006,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកស្វាយទាប",
                "en_name" => "Svay Teab",
                "branch_id" => 20,
                "sub_branch_id" => 2007,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាវិត",
                "en_name" => "Bavet",
                "branch_id" => 20,
                "sub_branch_id" => 2008,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអង្គរបូរី",
                "en_name" => "Angkor Borei",
                "branch_id" => 21,
                "sub_branch_id" => 2101,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបាទី",
                "en_name" => "Bati",
                "branch_id" => 21,
                "sub_branch_id" => 2102,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបូរីជលសារ",
                "en_name" => "Borei Cholsar",
                "branch_id" => 21,
                "sub_branch_id" => 2103,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកគីរីវង់",
                "en_name" => "Kiri Vong",
                "branch_id" => 21,
                "sub_branch_id" => 2104,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកោះអណ្ដែត",
                "en_name" => "Kaoh Andaet",
                "branch_id" => 21,
                "sub_branch_id" => 2105,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកព្រៃកប្បាស",
                "en_name" => "Prey Kabbas",
                "branch_id" => 21,
                "sub_branch_id" => 2106,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសំរោង",
                "en_name" => "Samraong",
                "branch_id" => 21,
                "sub_branch_id" => 2107,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកដូនកែវ",
                "en_name" => "Doun Kaev",
                "branch_id" => 21,
                "sub_branch_id" => 2108,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកត្រាំកក់",
                "en_name" => "Tram Kak",
                "branch_id" => 21,
                "sub_branch_id" => 2109,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកទ្រាំង",
                "en_name" => "Treang",
                "branch_id" => 21,
                "sub_branch_id" => 2110,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអន្លង់វែង",
                "en_name" => "Anlong Veaeng",
                "branch_id" => 22,
                "sub_branch_id" => 2201,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកបន្ទាយអំពិល",
                "en_name" => "Banteay Ampil",
                "branch_id" => 22,
                "sub_branch_id" => 2202,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកចុងកាល់",
                "en_name" => "Chong Kal",
                "branch_id" => 22,
                "sub_branch_id" => 2203,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសំរោង",
                "en_name" => "Samraong",
                "branch_id" => 22,
                "sub_branch_id" => 2204,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកត្រពាំងប្រាសាទ",
                "en_name" => "Trapeang Prasat",
                "branch_id" => 22,
                "sub_branch_id" => 2205,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកដំណាក់ចង្អើរ",
                "en_name" => "Damnak Changaeur",
                "branch_id" => 23,
                "sub_branch_id" => 2301,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកកែប",
                "en_name" => "Kaeb",
                "branch_id" => 23,
                "sub_branch_id" => 2302,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកប៉ៃលិន",
                "en_name" => "Pailin",
                "branch_id" => 24,
                "sub_branch_id" => 2401,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសាលាក្រៅ",
                "en_name" => "Sala Krau",
                "branch_id" => 24,
                "sub_branch_id" => 2402,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកតំបែរ",
                "en_name" => "Dambae",
                "branch_id" => 25,
                "sub_branch_id" => 2501,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកក្រូចឆ្មារ",
                "en_name" => "Krouch Chhmar",
                "branch_id" => 25,
                "sub_branch_id" => 2502,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកមេមត់",
                "en_name" => "Memot",
                "branch_id" => 25,
                "sub_branch_id" => 2503,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកអូររាំងឪ",
                "en_name" => "Ou Reang Ov",
                "branch_id" => 25,
                "sub_branch_id" => 2504,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកពញាក្រែក",
                "en_name" => "Ponhea Kraek",
                "branch_id" => 25,
                "sub_branch_id" => 2505,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកសួង",
                "en_name" => "Suong",
                "branch_id" => 25,
                "sub_branch_id" => 2506,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
            [
                "kh_name" => "គណ:កិត្តិយសអនុសាខា ស្រុកត្បូងឃ្មុំ",
                "en_name" => "Tboung Khmum",
                "branch_id" => 25,
                "sub_branch_id" => 2507,
                'committee_type_id' => 1,
                "committee_level_id" => 3,
            ],
        ]);
    }
}
