<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class OldUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permission = Permission::create(['name' => 'attendance', 'kh_name' => 'វត្តមាន',]);
        $role = Role::create(['name' => 'Officer', 'kh_name' => 'មន្ត្រី']);

        $role->givePermissionTo($permission);

        $users = [
            [
                'id' => '0MbNYc8zfLZdWeOr8xD69ZRVjso1',
                'email' => '010257364@admin.com',
                'name' => 'សាំង ផល្លី',
                'password' => Hash::make('010257364'),
                'kh_name' => 'សាំង ផល្លី',
                'phone_number' => '010257364',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'សន្តិសុខ',
                'department_position_order' => 15,
            ],
            [
                'id' => '0XG2FnjXSdQhDxYnRHQhpzI1Xx92',
                'email' => '011624883@admin.com',
                'name' => 'ឈិត រ៉េត',
                'password' => Hash::make('011624883'),
                'kh_name' => 'ឈិត រ៉េត',
                'phone_number' => '011624883',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'មន្ត្រីបើកបរ រថយន្តធុនធំ',
                'department_position_order' => 20,
            ],
            [
                'id' => '0XdyxCIHqhSmfZlbz1hfus45RQH3',
                'email' => '089202073@admin.com',
                'name' => 'អន ចំរើន',
                'password' => Hash::make('089202073'),
                'kh_name' => 'អន ចំរើន',
                'phone_number' => '089202073',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'អ​នុប្រធានការិយាល័យភស្តុភារ',
                'department_position_order' => 4,
            ],
            [
                'id' => '1UQs3a4h0XcaugK5y7QRmGwYkH93',
                'email' => '012813733@admin.com',
                'name' => 'ចាន់ សម្បត្តិ',
                'password' => Hash::make('012813733'),
                'kh_name' => 'ចាន់ សម្បត្តិ',
                'phone_number' => '012813733',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកជាប់កិច្ចសន្យា',
                'department_position_order' => 28,
            ],
            [
                'id' => '1eXpyoupxLX5k9stGwhUdKPrpAh1',
                'email' => '012688081@admin.com',
                'name' => 'សុខ ឡុង',
                'password' => Hash::make('012688081'),
                'kh_name' => 'សុខ ឡុង',
                'phone_number' => '012688081',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'នាយក នាយកដ្ឋានសុខភាព',
                'department_position_order' => 1,
            ],
            [
                'id' => '28qoXfMSsvWwfCBqendXPihDJwL2',
                'email' => '017248888@admin.com',
                'name' => 'ឌួង អេលីត',
                'password' => Hash::make('017248888'),
                'kh_name' => 'ឌួង អេលីត',
                'phone_number' => '017248888',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'នាយក ពិធីការ',
                'department_position_order' => 4,
            ],
            [
                'id' => '302xsFF5wRhcdGeCghwZVFrWHhk1',
                'email' => '0977766199@admin.com',
                'name' => 'គង់​ យ៉ានី',
                'password' => Hash::make('0977766199'),
                'kh_name' => 'គង់​ យ៉ានី',
                'phone_number' => '0977766199',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'ប្រធានការិយាល័យបុគ្គលិក',
                'department_position_order' => 100,
            ],
            [
                'id' => '564BwOIfeMbsHSx2ah36h9JrQHq2',
                'email' => '078450496@admin.com',
                'name' => 'កៀង វឌ្ឍន:',
                'password' => Hash::make('078450496'),
                'kh_name' => 'កៀង វឌ្ឍន:',
                'phone_number' => '078450496',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'ជំនួយការអគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 7,
            ],
            [
                'id' => '6JP7cqEF28UYzaQJd34dg8hqEGl2',
                'email' => '0976959666@admin.com',
                'name' => 'គេនអន',
                'password' => Hash::make('0976959666'),
                'kh_name' => 'គេនអន',
                'phone_number' => '0976959666',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'ជំនួយការការិយាល័យសង្រ្គោះបឋម',
                'department_position_order' => 6,
            ],
            [
                'id' => '6g14sDlYKkbYRDSdpU0etZTjZu83',
                'email' => '078224448@admin.com',
                'name' => 'ស៊ន​ សុទ្ធាបញ្ញា​',
                'password' => Hash::make('078224448'),
                'kh_name' => 'ស៊ន​ សុទ្ធាបញ្ញា​',
                'phone_number' => '078224448',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'ប្រធានការិយាល័យផ្សព្វផ្សាយ',
                'department_position_order' => 7,
            ],
            [
                'id' => '7JV7OWRekJcFQpfjqjHW2kWTMeA2',
                'email' => '012963966@admin.com',
                'name' => 'អ៊ិត ឬទ្ធី',
                'password' => Hash::make('012963966'),
                'kh_name' => 'អ៊ិត ឬទ្ធី',
                'phone_number' => '012963966',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'បើកបររថយន្ត',
                'department_position_order' => 9,
            ],
            [
                'id' => '7QyFM1TzzngcrH3lJ6lcAkNwZdl1',
                'email' => '017610526@admin.com',
                'name' => 'ស៊ូ សុខណា',
                'password' => Hash::make('017610526'),
                'kh_name' => 'ស៊ូ សុខណា',
                'phone_number' => '017610526',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'មន្ត្រីសម្របសម្រួលយុវជន និងអ្នកស្ម័គ្រចិត្ត',
                'department_position_order' => 6,
            ],
            [
                'id' => '8QREa7spoVPJ2wDea5AMDp6nqMa2',
                'email' => '078681800@admin.com',
                'name' => 'លុយ កូឡាប',
                'password' => Hash::make('078681800'),
                'kh_name' => 'លុយ កូឡាប',
                'phone_number' => '078681800',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'អនុប្រធានការិយាល័យអភិវឌ្ឍន៍',
                'department_position_order' => 5,
            ],
            [
                'id' => '9R2KTcHhFXMjCjU8f96D6cD4qAA3',
                'email' => '012715341@admin.com',
                'name' => 'ហួត ចេងឆាយ',
                'password' => Hash::make('012715341'),
                'kh_name' => 'ហួត ចេងឆាយ',
                'phone_number' => '012715341',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'ប្រធានការិយាល័យទំនាក់ទំនងសាធារណះ',
                'department_position_order' => 5,
            ],
            [
                'id' => '9b2jBZeRgkSU9legLq8HwsuMbmq1',
                'email' => '095929925@admin.com',
                'name' => 'លឹម សាយ',
                'password' => Hash::make('095929925'),
                'kh_name' => 'លឹម សាយ',
                'phone_number' => '095929925',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'នាយក​ នាយកដ្ឋានរដ្ឋបាល និងហិរញ្ញកិច្ច',
                'department_position_order' => 1,
            ],
            [
                'id' => 'AKBzafb5qHdwNKMgCLsMaedhWtv2',
                'email' => '017650997@admin.com',
                'name' => 'អ៊ឹង  សំភែល',
                'password' => Hash::make('017650997'),
                'kh_name' => 'អ៊ឹង  សំភែល',
                'phone_number' => '017650997',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'យន្តការី',
                'department_position_order' => 19,
            ],
            [
                'id' => 'Ah6hBTLmKOcUrFI9PuvDXXfUWZJ2',
                'email' => '០១៦៨៤០០៥៧@admin.com',
                'name' => 'អុប ពុទ្ធា',
                'password' => Hash::make('០១៦៨៤០០៥៧'),
                'kh_name' => 'អុប ពុទ្ធា',
                'phone_number' => '០១៦៨៤០០៥៧',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'ប្រធានការិយាល័យសង្គ្រោះបឋម',
                'department_position_order' => 3,
            ],
            [
                'id' => 'BKtnUOXuEDb22M2gA8K0NFSu7Cw1',
                'email' => '017222080@admin.com',
                'name' => 'test',
                'password' => Hash::make('017222080'),
                'kh_name' => 'test',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'test',
                'department_position_order' => 100,
            ],
            [
                'id' => 'BaJg2HOwBbfx4EtLVAQbNCGTkMz2',
                'email' => '0968177925@admin.com',
                'name' => 'នួន រមណី',
                'password' => Hash::make('0968177925'),
                'kh_name' => 'នួន រមណី',
                'phone_number' => '0968177925',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'មន្រ្តីសម្របសម្រួលគម្រោងកសាងភាពធន់សហគមន៍',
                'department_position_order' => 100,
            ],
            [
                'id' => 'BqC7OnBPRoh6EUGPJTnggmKaYny1',
                'email' => '098998566@admin.com',
                'name' => 'ពុំ ឆៃយ៉ាវណ្ណ',
                'password' => Hash::make('098998566'),
                'kh_name' => 'ពុំ ឆៃយ៉ាវណ្ណ',
                'phone_number' => '098998566',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'មន្រ្តីអភិវឌ្ឍន៍យុវជន និងអ្នកស្ម័គ្រចិត្ត',
                'department_position_order' => 8,
            ],
            [
                'id' => 'CMoN7HIaWrdB4vT2pGtXBMKrs8k1',
                'email' => '017445964@admin.com',
                'name' => 'រឿត​ សុខុន',
                'password' => Hash::make('017445964'),
                'kh_name' => 'រឿត​ សុខុន',
                'phone_number' => '017445964',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'នាយករង នាយកដ្ឋានធនធានមនុស្ស',
                'department_position_order' => 2,
            ],
            [
                'id' => 'CNN5eW1HTiSt34USEbJWcX7sWG22',
                'email' => '0969077771@admin.com',
                'name' => 'យ៉ា សុផាត',
                'password' => Hash::make('0969077771'),
                'kh_name' => 'យ៉ា សុផាត',
                'phone_number' => '0969077771',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'First Aid Instructor ',
                'department_position_order' => 5,
            ],
            [
                'id' => 'E4LUuTZYxgPdLGH1f4df3bKV3Uh2',
                'email' => '016666466@admin.com',
                'name' => 'ឌី ដារ៉ា',
                'password' => Hash::make('016666466'),
                'kh_name' => 'ឌី ដារ៉ា',
                'phone_number' => '016666466',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'មន្ត្រីឥណទាយី',
                'department_position_order' => 10,
            ],
            [
                'id' => 'EgBVOHx3QmVGPKVzWNqpZVSYdP92',
                'email' => '017222080@admin.com',
                'name' => 'មុំ ចន្ធី',
                'password' => Hash::make('017222080'),
                'kh_name' => 'មុំ ចន្ធី',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'នាយិការង នាយកដ្ឋានសុខភាព',
                'department_position_order' => 2,
            ],
            [
                'id' => 'EwZFzk2TzTcyscgm1Rpa95Z8qat1',
                'email' => '012454726@admin.com',
                'name' => ' ឯម មី',
                'password' => Hash::make('012454726'),
                'kh_name' => ' ឯម មី',
                'phone_number' => '012454726',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'ប្រធានក្រុមអនាម័យ',
                'department_position_order' => 14,
            ],
            [
                'id' => 'FxjIx0atSfSlgiK5yOz0nwIJ1rj2',
                'email' => '077750705@admin.com',
                'name' => 'ឯម​ សុម៉ាលីតា',
                'password' => Hash::make('077750705'),
                'kh_name' => 'ឯម​ សុម៉ាលីតា',
                'phone_number' => '077750705',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'បុគ្គលិកអនាម័យ',
                'department_position_order' => 15,
            ],
            [
                'id' => 'G8wXuIfT24c3CcKTHUs98TI751h1',
                'email' => '០១៧​៣៧៥៧៨៨@admin.com',
                'name' => 'សេង​ ប៉ុណ្ណារា',
                'password' => Hash::make('០១៧​៣៧៥៧៨៨'),
                'kh_name' => 'សេង​ ប៉ុណ្ណារា',
                'phone_number' => '០១៧​៣៧៥៧៨៨',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'នាំក្បួនរថយន្តនឹងរៀបចំារងារចែកចាយ',
                'department_position_order' => 6,
            ],
            [
                'id' => 'GOOHbEOJlaMDEgrtk4loQp8SXyC3',
                'email' => '092788055@admin.com',
                'name' => 'អ៊ូរ ចាន់ធាវី',
                'password' => Hash::make('092788055'),
                'kh_name' => 'អ៊ូរ ចាន់ធាវី',
                'phone_number' => '092788055',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'នាយិការង នាយកដ្ឋានរដ្ឋ​បាល ហិរញ្ញកិច្ច',
                'department_position_order' => 2,
            ],
            [
                'id' => 'HT5OVUL4bIMh3BhikpfcTWgZmfQ2',
                'email' => '099333888@admin.com',
                'name' => 'វ៉ា សុភ័ក្រ្ត',
                'password' => Hash::make('099333888'),
                'kh_name' => 'វ៉ា សុភ័ក្រ្ត',
                'phone_number' => '099333888',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'ប្រធានការិយាល័យការពារជម្ងឺឆ្លង',
                'department_position_order' => 9,
            ],
            [
                'id' => 'Hba97Hx9k2hq1tjEoY98ttldgcT2',
                'email' => '012354988@admin.com',
                'name' => 'ស៊ូ សុតារា',
                'password' => Hash::make('012354988'),
                'kh_name' => 'ស៊ូ សុតារា',
                'phone_number' => '012354988',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'Hello',
                'department_position_order' => 200,
            ],
            [
                'id' => 'HgTvq7ToybdKNibP8norya5ho9l1',
                'email' => '017222080@admin.com',
                'name' => 'ហង់ ចាន់សាណា',
                'password' => Hash::make('017222080'),
                'kh_name' => 'ហង់ ចាន់សាណា',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => '',
                'department_position_order' => 100,
            ],
            [
                'id' => 'IowXUboWEEhRTm9QBMGi46H3DuP2',
                'email' => '078 22 44 49@admin.com',
                'name' => 'ឌួង​ ទេពសុគន្ធា',
                'password' => Hash::make('078 22 44 49'),
                'kh_name' => 'ឌួង​ ទេពសុគន្ធា',
                'phone_number' => '078 22 44 49',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'មន្រ្តីអភិវឌ្ឍន៍យុវជន និងអ្នកស្ម័គ្រចិត្ត',
                'department_position_order' => 7,
            ],
            [
                'id' => 'JPeomj4GjnS7Zh5udwmU5cmASru2',
                'email' => '012846357@admin.com',
                'name' => 'ឡាក់ មុនីរស្មី',
                'password' => Hash::make('012846357'),
                'kh_name' => 'ឡាក់ មុនីរស្មី',
                'phone_number' => '012846357',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'ជំនួយការអគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 9,
            ],
            [
                'id' => 'JgzDO1ygLxaqoKB6SWWE07zZ3bl2',
                'email' => '012289576@admin.com',
                'name' => 'យូ​ ឡាណា',
                'password' => Hash::make('012289576'),
                'kh_name' => 'យូ​ ឡាណា',
                'phone_number' => '012289576',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'អគ្គរងទី​២',
                'department_position_order' => 3,
            ],
            [
                'id' => 'KFHYPsRHHbbqrMdAijgG0EVJIKZ2',
                'email' => '017873210@admin.com',
                'name' => 'នាង នារីឆាយារ័ត្ន',
                'password' => Hash::make('017873210'),
                'kh_name' => 'នាង នារីឆាយារ័ត្ន',
                'phone_number' => '017873210',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'មន្ត្រីឥណទាយី',
                'department_position_order' => 9,
            ],
            [
                'id' => 'MxTdTxMEpCSCVLdyI446aHMlLyB3',
                'email' => '017222080@admin.com',
                'name' => 'test4',
                'password' => Hash::make('017222080'),
                'kh_name' => 'test4',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'test4',
                'department_position_order' => 100,
            ],
            [
                'id' => 'NFpJNTcMF0eFmwVdVcxJ5V9mJl52',
                'email' => '012371820@admin.com',
                'name' => 'នូ បុប្ផាម៉ាលី',
                'password' => Hash::make('012371820'),
                'kh_name' => 'នូ បុប្ផាម៉ាលី',
                'phone_number' => '012371820',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'មន្រ្តីបំរើភេសជ្ជ:',
                'department_position_order' => 19,
            ],
            [
                'id' => 'NY5g0EVOwoPWuyLXAGb2KB4yrK93',
                'email' => '092652111@admin.com',
                'name' => 'គិម ប៊ុនថាណា',
                'password' => Hash::make('092652111'),
                'kh_name' => 'គិម ប៊ុនថាណា',
                'phone_number' => '092652111',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'អនុប្រធានការិយាល័យគណនេយ្យ',
                'department_position_order' => 6,
            ],
            [
                'id' => 'O3SAPLYseuTv4hSJxVVgRL5QstD2',
                'email' => '012311611@admin.com',
                'name' => 'ហួនចន្ទបូរ៉ា',
                'password' => Hash::make('012311611'),
                'kh_name' => 'ហួនចន្ទបូរ៉ា',
                'phone_number' => '012311611',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'នាយិកា',
                'department_position_order' => 1,
            ],
            [
                'id' => 'OHmenPntfEQsbeo83sqmHdWdov03',
                'email' => '012966886@admin.com',
                'name' => 'អ៊ុយ សំអាត',
                'password' => Hash::make('012966886'),
                'kh_name' => 'អ៊ុយ សំអាត',
                'phone_number' => '012966886',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'ជំនួយការ',
                'department_position_order' => 5,
            ],
            [
                'id' => 'OSQfo5wGmXgKmuXhJBxbLT7z9f72',
                'email' => '017955865@admin.com',
                'name' => 'គង់វង្ស សីហ៍វិសាល',
                'password' => Hash::make('017955865'),
                'kh_name' => 'គង់វង្ស សីហ៍វិសាល',
                'phone_number' => '017955865',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'ប្រធានការិ. អប់រំផ្សព្វផ្សាយពីមីន និងទំនាក់ទំនងគ្រួសារ',
                'department_position_order' => 9,
            ],
            [
                'id' => 'OWOfFy2hLWbsEviMn5VMgde9RUG3',
                'email' => '012838030@admin.com',
                'name' => 'ព្រូ លាប',
                'password' => Hash::make('012838030'),
                'kh_name' => 'ព្រូ លាប',
                'phone_number' => '012838030',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'មន្រ្តីនាយកដ្ឋានសុខភាព',
                'department_position_order' => 4,
            ],
            [
                'id' => 'OgP7dUfToSRA0iNq0A8FScIc5392',
                'email' => '015809746@admin.com',
                'name' => 'ជា​ រតន:',
                'password' => Hash::make('015809746'),
                'kh_name' => 'ជា​ រតន:',
                'phone_number' => '015809746',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'អ្នកស្ម័គ្រចិត្ត​',
                'department_position_order' => 24,
            ],
            [
                'id' => 'Pte5QgcCKFYJUgY7wg8nO6YdQFv1',
                'email' => '012229191@admin.com',
                'name' => 'ម៉ម ដារ៉ូ',
                'password' => Hash::make('012229191'),
                'kh_name' => 'ម៉ម ដារ៉ូ',
                'phone_number' => '012229191',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'អនុប្រធានការិយាល័យស្តារទំនាក់ទំនងគ្រួសារ',
                'department_position_order' => 10,
            ],
            [
                'id' => 'R5eHwk7TE2c3IkBcgeS9b2i9EnN2',
                'email' => '077394444@admin.com',
                'name' => 'ឆន រ័ត្នចាន់ដានី',
                'password' => Hash::make('077394444'),
                'kh_name' => 'ឆន រ័ត្នចាន់ដានី',
                'phone_number' => '077394444',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'មន្រ្តីកៀរគររកមូលនិធិ',
                'department_position_order' => 4,
            ],
            [
                'id' => 'RFVCdIkGNmSJzRpdX8vj80EAG4I2',
                'email' => '០១៧៩៥៥៨៦៥@admin.com',
                'name' => 'គង់វង្ស សីហ៍វិសាល',
                'password' => Hash::make('០១៧៩៥៥៨៦៥'),
                'kh_name' => 'គង់វង្ស សីហ៍វិសាល',
                'phone_number' => '០១៧៩៥៥៨៦៥',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'ប្រធានការិយាល័យផ្សព្វផ្សាយ',
                'department_position_order' => 9,
            ],
            [
                'id' => 'RtZAMvy7WHbB0PdT8jhytsaYu4T2',
                'email' => '012921105@admin.com',
                'name' => 'ពុំ ចន្ទីនី',
                'password' => Hash::make('012921105'),
                'kh_name' => 'ពុំ ចន្ទីនី',
                'phone_number' => '012921105',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'អគ្គលេខាធិការ',
                'department_position_order' => 1,
            ],
            [
                'id' => 'S6usWZfkvBYPRvB00wJcQXlW2r32',
                'email' => '099999665@admin.com',
                'name' => 'យ៉ា សុផាត',
                'password' => Hash::make('099999665'),
                'kh_name' => 'យ៉ា សុផាត',
                'phone_number' => '099999665',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'First Aid Instructor ',
                'department_position_order' => 5,
            ],
            [
                'id' => 'S9kvUNXVpFhAkDBBXzFyBSbLmCq1',
                'email' => '017525566@admin.com',
                'name' => 'ណុប សុធា',
                'password' => Hash::make('017525566'),
                'kh_name' => 'ណុប សុធា',
                'phone_number' => '017525566',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'ប្រធានការិយាល័យកៀរគរមូលនិធិ',
                'department_position_order' => 3,
            ],
            [
                'id' => 'ShL6JxFzrgdZFBToiIPGE3xvdwr1',
                'email' => '077686786@admin.com',
                'name' => 'ភន គឹមហឿង',
                'password' => Hash::make('077686786'),
                'kh_name' => 'ភន គឹមហឿង',
                'phone_number' => '077686786',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'មន្រ្តីការិយាល័យការពារជំងឺឆ្លង-មិនឆ្លង',
                'department_position_order' => 10,
            ],
            [
                'id' => 'TnxgQDPRBXUOwvkhNUhP7QKdPFZ2',
                'email' => '012930017@admin.com',
                'name' => 'អ៊ុន.វី',
                'password' => Hash::make('012930017'),
                'kh_name' => 'អ៊ុន.វី',
                'phone_number' => '012930017',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'សន្តិសុខ',
                'department_position_order' => 13,
            ],
            [
                'id' => 'UKFJamqOXlbkMBWC711NUJTi18m1',
                'email' => '095597798@admin.com',
                'name' => 'ហែម សារាវុធ',
                'password' => Hash::make('095597798'),
                'kh_name' => 'ហែម សារាវុធ',
                'phone_number' => '095597798',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'ការីកុំព្យូទ័រ',
                'department_position_order' => 12,
            ],
            [
                'id' => 'UOcD6lW2NnaHKiI6Bhy2Gu6fTl72',
                'email' => '012798982@admin.com',
                'name' => 'សំ វន្ថា',
                'password' => Hash::make('012798982'),
                'kh_name' => 'សំ វន្ថា',
                'phone_number' => '012798982',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'លេខាធិការ អគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 12,
            ],
            [
                'id' => 'UQjQjg1qdiWGjpLDnardezsT6aw2',
                'email' => '012930017@admin.com',
                'name' => 'អ៊ុន.វី',
                'password' => Hash::make('012930017'),
                'kh_name' => 'អ៊ុន.វី',
                'phone_number' => '012930017',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'សន្តិសុខ',
                'department_position_order' => 13,
            ],
            [
                'id' => 'US4fm3WLNpVNK7CIETNn7DhHzvX2',
                'email' => '098571158@admin.com',
                'name' => 'ផង់ ប៉ុណ្ណា',
                'password' => Hash::make('098571158'),
                'kh_name' => 'ផង់ ប៉ុណ្ណា',
                'phone_number' => '098571158',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បើកបររថយន្ត',
                'department_position_order' => 12,
            ],
            [
                'id' => 'V1lEWdglQNbrQ1wdfYry32njx7j2',
                'email' => '077991046@admin.com',
                'name' => 'ហ៊ុយ ឆេងតារាផល',
                'password' => Hash::make('077991046'),
                'kh_name' => 'ហ៊ុយ ឆេងតារាផល',
                'phone_number' => '077991046',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកសន្តិសុខ',
                'department_position_order' => 16,
            ],
            [
                'id' => 'VNMipbmjGHdAaubl7fq9hlpaydB2',
                'email' => '017707064@admin.com',
                'name' => 'សោម សេរីវឌ្ឍន៍',
                'password' => Hash::make('017707064'),
                'kh_name' => 'សោម សេរីវឌ្ឍន៍',
                'phone_number' => '017707064',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'ជំនួយការអគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 6,
            ],
            [
                'id' => 'WCrej4E51PMqivlNvDVYo4euvZG3',
                'email' => '068610526@admin.com',
                'name' => 'ស៊ូ សុខណា',
                'password' => Hash::make('068610526'),
                'kh_name' => 'ស៊ូ សុខណា',
                'phone_number' => '068610526',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'មន្ត្រីសម្របសម្រួលយុវជន និងអ្នកស្ម័គ្រចិត្ត',
                'department_position_order' => 6,
            ],
            [
                'id' => 'XVeRwzIc8yPighumMCkTIfxZUQI2',
                'email' => '081822253@admin.com',
                'name' => 'ហាក់ ភិចសៀន',
                'password' => Hash::make('081822253'),
                'kh_name' => 'ហាក់ ភិចសៀន',
                'phone_number' => '081822253',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'អ្នកស្ម័គ្រចិត្ត',
                'department_position_order' => 13,
            ],
            [
                'id' => 'XfKVcLP05iSFZBaYYKNs96RX6Wy2',
                'email' => '0977766199@admin.com',
                'name' => 'គង់ យ៉ានី',
                'password' => Hash::make('0977766199'),
                'kh_name' => 'គង់ យ៉ានី',
                'phone_number' => '0977766199',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'ប្រធានការិយាល័យបុគ្គលិក',
                'department_position_order' => 3,
            ],
            [
                'id' => 'XnJAcqkTRuQ6vhFMyahZ4qeTYxf1',
                'email' => '081367293@admin.com',
                'name' => 'សាំង ផល្លី',
                'password' => Hash::make('081367293'),
                'kh_name' => 'សាំង ផល្លី',
                'phone_number' => '081367293',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'សន្តិសុខ',
                'department_position_order' => 100,
            ],
            [
                'id' => 'Y8xGI4yTvMPBuR5LUBZAkbwPgQi2',
                'email' => '017838823@admin.com',
                'name' => 'រស់ ចន្ទផល្លី',
                'password' => Hash::make('017838823'),
                'kh_name' => 'រស់ ចន្ទផល្លី',
                'phone_number' => '017838823',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'នាយិការង ពិធីការ',
                'department_position_order' => 8,
            ],
            [
                'id' => 'YJDeVT4naIZj0YabxUv7Q1evSK43',
                'email' => '017812988@admin.com',
                'name' => 'ជុំ សារ៉េត',
                'password' => Hash::make('017812988'),
                'kh_name' => 'ជុំ សារ៉េត',
                'phone_number' => '017812988',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'ជាងភ្លើង',
                'department_position_order' => 21,
            ],
            [
                'id' => 'YZyixB3kqUaJxMmHsq0z1BgYyAm2',
                'email' => '092744188@admin.com',
                'name' => 'ពិន រង់',
                'password' => Hash::make('092744188'),
                'kh_name' => 'ពិន រង់',
                'phone_number' => '092744188',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'ពលករឃ្លាំង-បច្ចេកទេសជាង',
                'department_position_order' => 18,
            ],
            [
                'id' => 'ZD9bC23eYGgoPyQRfDnh7GXg0eH3',
                'email' => '012201455@admin.com',
                'name' => 'ហង់ ចាន់សាណា',
                'password' => Hash::make('012201455'),
                'kh_name' => 'ហង់ ចាន់សាណា',
                'phone_number' => '012201455',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'ប្រធានការិយាល័យសុខភាពគ្រាអាសន្ន',
                'department_position_order' => 7,
            ],
            [
                'id' => 'Zws9kA7N9SeeJPGVnKKFGd0SP8B2',
                'email' => '017957523@admin.com',
                'name' => 'ឃឹម ហ៊ាង',
                'password' => Hash::make('017957523'),
                'kh_name' => 'ឃឹម ហ៊ាង',
                'phone_number' => '017957523',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'បុគ្គលិកបើកបររថយន្តធំ/តូច',
                'department_position_order' => 10,
            ],
            [
                'id' => 'ajAT0ISBVBYfrvtoXzTCF5f4WYh2',
                'email' => '011511858@admin.com',
                'name' => 'វ៉ា សិរី',
                'password' => Hash::make('011511858'),
                'kh_name' => 'វ៉ា សិរី',
                'phone_number' => '011511858',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'មន្ត្រីភេសជ្ជៈ',
                'department_position_order' => 18,
            ],
            [
                'id' => 'bA0n5b6rt5ebJXPtb3Nuk3z2YqB3',
                'email' => '99999665@admin.com',
                'name' => 'យ៉ា សុផាត',
                'password' => Hash::make('99999665'),
                'kh_name' => 'យ៉ា សុផាត',
                'phone_number' => '99999665',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'First Aid Instructor ',
                'department_position_order' => 5,
            ],
            [
                'id' => 'bRJRCqaV9adfznulrcA1NUDOtkH3',
                'email' => '017303011@admin.com',
                'name' => 'អ៊ុយ វិចិត្រ',
                'password' => Hash::make('017303011'),
                'kh_name' => 'អ៊ុយ វិចិត្រ',
                'phone_number' => '017303011',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'មន្ត្រីកត់ត្រាសម្ភារះឃ្លាំង',
                'department_position_order' => 5,
            ],
            [
                'id' => 'cmtRPMK2yahhUQhxaJOqoLZHMLK2',
                'email' => '012416807@admin.com',
                'name' => 'សុខ ថារ៉េត',
                'password' => Hash::make('012416807'),
                'kh_name' => 'សុខ ថារ៉េត',
                'phone_number' => '012416807',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកបើកបររថយន្តធំ/តូច',
                'department_position_order' => 11,
            ],
            [
                'id' => 'cxSN9llkNKQiIcWpwPWcgyrIApF3',
                'email' => '012810854@admin.com',
                'name' => 'ម៉ែន នារីសោភ័គ',
                'password' => Hash::make('012810854'),
                'kh_name' => 'ម៉ែន នារីសោភ័គ',
                'phone_number' => '012810854',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'អគ្គលេខាធិការរងទី ១',
                'department_position_order' => 2,
            ],
            [
                'id' => 'dW6g927INYXgsvhaQYRfGi8A0eI3',
                'email' => '017222080@admin.com',
                'name' => 'យូ​ ឡាណា​',
                'password' => Hash::make('017222080'),
                'kh_name' => 'យូ​ ឡាណា​',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'អគ្គរងទី​២',
                'department_position_order' => 20,
            ],
            [
                'id' => 'dduKzdrVC4c6MShqLZxTyNbQwgs2',
                'email' => '012555737@admin.com',
                'name' => 'ឃុន​ សាម៉េង',
                'password' => Hash::make('012555737'),
                'kh_name' => 'ឃុន​ សាម៉េង',
                'phone_number' => '012555737',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'នាយក​ នាយកដ្ឋានធនធានមនុស្ស',
                'department_position_order' => 1,
            ],
            [
                'id' => 'dhdLApEe5sQlC6ZphIlUreem9N63',
                'email' => '011795366@admin.com',
                'name' => 'ហ៊ី  ម៉ារីណា',
                'password' => Hash::make('011795366'),
                'kh_name' => 'ហ៊ី  ម៉ារីណា',
                'phone_number' => '011795366',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'ជំនួយការអគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 11,
            ],
            [
                'id' => 'f1U5zKlVz3MzMNuWralGwKDn9PX2',
                'email' => '០១៧៩៥៧៥២៣@admin.com',
                'name' => 'ឃឹម ហ៊ាង',
                'password' => Hash::make('០១៧៩៥៧៥២៣'),
                'kh_name' => 'ឃឹម ហ៊ាង',
                'phone_number' => '០១៧៩៥៧៥២៣',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'បើកបរ',
                'department_position_order' => 100,
            ],
            [
                'id' => 'fqQ7WV7thPQtsIXoEnjRODg8IH23',
                'email' => '077324494@admin.com',
                'name' => 'សេង ស្រីអូន',
                'password' => Hash::make('077324494'),
                'kh_name' => 'សេង ស្រីអូន',
                'phone_number' => '077324494',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'អ្នកស្ម័គ្រចិត្ត',
                'department_position_order' => 12,
            ],
            [
                'id' => 'g14JCNlch4d75k3IXkGMu9vRJT52',
                'email' => '017222080@admin.com',
                'name' => 'test',
                'password' => Hash::make('017222080'),
                'kh_name' => 'test',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'test',
                'department_position_order' => 100,
            ],
            [
                'id' => 'hQFCZnpLKfStHIZGJCuJbp4Tgnh1',
                'email' => '012722074@admin.com',
                'name' => 'មំុ ភិរក្ស',
                'password' => Hash::make('012722074'),
                'kh_name' => 'មំុ ភិរក្ស',
                'phone_number' => '012722074',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'នាយករង​ នាយកដ្ឋានទំនាក់ទំនង',
                'department_position_order' => 2,
            ],
            [
                'id' => 'hnN44M7YloOns1a8I8p0IBwXWV72',
                'email' => '011201700@admin.com',
                'name' => 'សួស ច័ន្ទតារា',
                'password' => Hash::make('011201700'),
                'kh_name' => 'សួស ច័ន្ទតារា',
                'phone_number' => '011201700',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'មន្ត្រីសរសេរអត្ថបទព័ត៌មាន',
                'department_position_order' => 11,
            ],
            [
                'id' => 'hwSpl9cFlVNxPm8rPIeNMntgt3o1',
                'email' => '012578986@admin.com',
                'name' => 'ពេជ្រ​ ចរិយា​',
                'password' => Hash::make('012578986'),
                'kh_name' => 'ពេជ្រ​ ចរិយា​',
                'phone_number' => '012578986',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'មន្រ្តីរដ្ឋបាល',
                'department_position_order' => 11,
            ],
            [
                'id' => 'i3pvTbmkXPe7r51PZlmHiBajSCh1',
                'email' => '017222080@admin.com',
                'name' => 'សាំង ផល្លី',
                'password' => Hash::make('017222080'),
                'kh_name' => 'សាំង ផល្លី',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'សន្តិសុខ',
                'department_position_order' => 100,
            ],
            [
                'id' => 'i72JN0reSIgv5Nq6i6s3VRiyYis2',
                'email' => '012731597@admin.com',
                'name' => 'ញ៉ឹក ស៊ីផុន',
                'password' => Hash::make('012731597'),
                'kh_name' => 'ញ៉ឹក ស៊ីផុន',
                'phone_number' => '012731597',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'ជំនួយការអគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 10,
            ],
            [
                'id' => 'iaIo7o2FqKcf6x0JtppIDZ9xNeQ2',
                'email' => '012282987@admin.com',
                'name' => 'ទូច ភក្តី',
                'password' => Hash::make('012282987'),
                'kh_name' => 'ទូច ភក្តី',
                'phone_number' => '012282987',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'អនុប្រធានការិយាល័យផ្សព្វផ្សាយ',
                'department_position_order' => 8,
            ],
            [
                'id' => 'iewBQtgYahZm5IXYif3kQA4vYaA2',
                'email' => '017222080@admin.com',
                'name' => 'ឃឹម ហ៊ាង',
                'password' => Hash::make('017222080'),
                'kh_name' => 'ឃឹម ហ៊ាង',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'បើកបរ',
                'department_position_order' => 100,
            ],
            [
                'id' => 'j7eZRN66LcVmJfx4WUVKREXv62E2',
                'email' => '012838030@admin.com',
                'name' => 'ព្រូ លាប',
                'password' => Hash::make('012838030'),
                'kh_name' => 'ព្រូ លាប',
                'phone_number' => '012838030',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'មន្រ្តីទីផ្សារវិជ្ជាសង្រ្គោះបឋម',
                'department_position_order' => 4,
            ],
            [
                'id' => 'kHLqco6gkLSk8ADz0UGbO3pSI732',
                'email' => '012519724@admin.com',
                'name' => 'លូង លឹម',
                'password' => Hash::make('012519724'),
                'kh_name' => 'លូង លឹម',
                'phone_number' => '012519724',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'មន្ត្រីបូកសរុបរបាយការណ៍',
                'department_position_order' => 7,
            ],
            [
                'id' => 'kIx8FBxY4jXy1U3XyYp1JceTbPE3',
                'email' => '០១៧៩៥៧៥២៣@admin.com',
                'name' => 'ឃឹម ហ៊ាង',
                'password' => Hash::make('០១៧៩៥៧៥២៣'),
                'kh_name' => 'ឃឹម ហ៊ាង',
                'phone_number' => '០១៧៩៥៧៥២៣',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'បើកបរ',
                'department_position_order' => 100,
            ],
            [
                'id' => 'kw3pPEq3LzXPFHm0LITNkQPuQi12',
                'email' => '095457788@admin.com',
                'name' => 'គង់ សំណាង',
                'password' => Hash::make('095457788'),
                'kh_name' => 'គង់ សំណាង',
                'phone_number' => '095457788',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'Deputy head of PMER',
                'department_position_order' => 4,
            ],
            [
                'id' => 'l3UouXUtArg8bVRF0SPtN912YRZ2',
                'email' => '092443293@admin.com',
                'name' => 'អ៊ុន វន់',
                'password' => Hash::make('092443293'),
                'kh_name' => 'អ៊ុន វន់',
                'phone_number' => '092443293',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'មន្ត្រី អនាម័យ',
                'department_position_order' => 16,
            ],
            [
                'id' => 'lx3Y8kGYCeShqX2GZkHLefBHgFH3',
                'email' => '092893691@admin.com',
                'name' => 'មុត ហ៊ុយ',
                'password' => Hash::make('092893691'),
                'kh_name' => 'មុត ហ៊ុយ',
                'phone_number' => '092893691',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកបើកបររថយន្តតូច',
                'department_position_order' => 23,
            ],
            [
                'id' => 'mAZSIHPfKScnzH3REI0qCNpmm1b2',
                'email' => '០១២-៩៣១-៤៣៤@admin.com',
                'name' => 'ឱម វុឌ្ឃរ៉ូ',
                'password' => Hash::make('០១២-៩៣១-៤៣៤'),
                'kh_name' => 'ឱម វុឌ្ឃរ៉ូ',
                'phone_number' => '០១២-៩៣១-៤៣៤',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'អ្នកស្ម័គ្រចិត្ត នាយកដ្ឋានសុខភាព',
                'department_position_order' => 11,
            ],
            [
                'id' => 'mSB10QAzRjcCrbL4O8PxUDT7LTw1',
                'email' => '012339121@admin.com',
                'name' => 'អ៊ឹង វិទ្យាធារ៉ា',
                'password' => Hash::make('012339121'),
                'kh_name' => 'អ៊ឹង វិទ្យាធារ៉ា',
                'phone_number' => '012339121',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'អនុប្រធានការិយាល័យទំនាក់ទំនងសាធារណៈ',
                'department_position_order' => 6,
            ],
            [
                'id' => 'n7u1Yiq8xxYKP5oFU6eJkhxta3l2',
                'email' => '012916949@admin.com',
                'name' => 'អ៊ុយ សំអុន',
                'password' => Hash::make('012916949'),
                'kh_name' => 'អ៊ុយ សំអុន',
                'phone_number' => '012916949',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'នាយកនាយកដ្ឋានគ្រប់គ្រងគ្រោះមហន្តរាយ',
                'department_position_order' => 1,
            ],
            [
                'id' => 'oGNY5KFbCrRAhxtod2SYihYj30i2',
                'email' => '011730949@admin.com',
                'name' => 'អ៊ុំ អូន',
                'password' => Hash::make('011730949'),
                'kh_name' => 'អ៊ុំ អូន',
                'phone_number' => '011730949',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកជាប់កិច្ចសន្យា',
                'department_position_order' => 25,
            ],
            [
                'id' => 'ptfnWqEij2WdzkIh7GOqLkfFQMN2',
                'email' => '012202371@admin.com',
                'name' => 'សេង ទឿ',
                'password' => Hash::make('012202371'),
                'kh_name' => 'សេង ទឿ',
                'phone_number' => '012202371',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកសន្តិសុខ',
                'department_position_order' => 17,
            ],
            [
                'id' => 'pyC4PGHpZxeQDoUBvU1vSv2wJUG3',
                'email' => '01012728151@admin.com',
                'name' => 'ជួប សណ្តាន',
                'password' => Hash::make('01012728151'),
                'kh_name' => 'ជួប សណ្តាន',
                'phone_number' => '01012728151',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បេីកបរ',
                'department_position_order' => 22,
            ],
            [
                'id' => 'q8YiqbGpyOYULP2bBJBKmUC2TpN2',
                'email' => '011493994@admin.com',
                'name' => 'ឌឹម វណ្ណថា',
                'password' => Hash::make('011493994'),
                'kh_name' => 'ឌឹម វណ្ណថា',
                'phone_number' => '011493994',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'មន្រ្តីកម្មវិធីពង្រឹងភាពជាដៃគូផ្តោតលើការបង្ការ និងឆ្លើយតបជំងឺរាតត្បាតផ្សេងៗ',
                'department_position_order' => 8,
            ],
            [
                'id' => 'qh2OusSHZZWyjeohYynln6vasVo2',
                'email' => '092101006@admin.com',
                'name' => 'ពុំ ភារ៉ាត',
                'password' => Hash::make('092101006'),
                'kh_name' => 'ពុំ ភារ៉ាត',
                'phone_number' => '092101006',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 1,
                'position' => 'លេខាធិការ អគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 13,
            ],
            [
                'id' => 'qjb1pYdlGneAYIf8jMgYb88nO7g1',
                'email' => '017222080@admin.com',
                'name' => 'test6',
                'password' => Hash::make('017222080'),
                'kh_name' => 'test6',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'test6',
                'department_position_order' => 20,
            ],
            [
                'id' => 'quy940873RMjZ2A4byQa9mFL9gK2',
                'email' => '089810068@admin.com',
                'name' => 'ឈិន រ៉ន',
                'password' => Hash::make('089810068'),
                'kh_name' => 'ឈិន រ៉ន',
                'phone_number' => '089810068',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកជាប់កិច្ចសន្យា',
                'department_position_order' => 26,
            ],
            [
                'id' => 'qvHKv4xHL5PRFSOQRK7OlMrz96N2',
                'email' => '012715341@admin.com',
                'name' => 'ហួត ចេងឆាយ',
                'password' => Hash::make('012715341'),
                'kh_name' => 'ហួត ចេងឆាយ',
                'phone_number' => '012715341',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 5,
                'position' => 'ប្រធានការិយាល័យទំនាក់ទំនងសាធារណះ',
                'department_position_order' => 5,
            ],
            [
                'id' => 'rPU67pQ2ocgRdm0W2rjNFnXADGu2',
                'email' => '012603855@admin.com',
                'name' => 'គាំ ស',
                'password' => Hash::make('012603855'),
                'kh_name' => 'គាំ ស',
                'phone_number' => '012603855',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកបើកបរ',
                'department_position_order' => 8,
            ],
            [
                'id' => 'rwO9Guq8a8areYkrh5wOeGkk7V92',
                'email' => '012229191@admin.com',
                'name' => 'ម៉ម ដារ៉ូ',
                'password' => Hash::make('012229191'),
                'kh_name' => 'ម៉ម ដារ៉ូ',
                'phone_number' => '012229191',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'អនុប្រធានការិយាល័យស្តារទំនាក់ទំនងគ្រួសារ',
                'department_position_order' => 10,
            ],
            [
                'id' => 'rwp5wOjG8KfqVliAMKuoj3hX44w2',
                'email' => '012246001@admin.com',
                'name' => 'សំ ណារី',
                'password' => Hash::make('012246001'),
                'kh_name' => 'សំ ណារី',
                'phone_number' => '012246001',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'បុគ្គលិកអនាម័យ',
                'department_position_order' => 17,
            ],
            [
                'id' => 's82rKDCEJZMAuDgJBUNOURvw54w1',
                'email' => '012275991@admin.com',
                'name' => 'នី​ ប៊ុនថា',
                'password' => Hash::make('012275991'),
                'kh_name' => 'នី​ ប៊ុនថា',
                'phone_number' => '012275991',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'ប្រធានការិយាល័យគណនេយ្យ',
                'department_position_order' => 5,
            ],
            [
                'id' => 'stR7HbS8kZY1pXRXSbBDI0AG6Wu2',
                'email' => '089780743@admin.com',
                'name' => 'ម៉ៅ ផល្លី',
                'password' => Hash::make('089780743'),
                'kh_name' => 'ម៉ៅ ផល្លី',
                'phone_number' => '089780743',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'មន្រ្តីចុះបញ្ជីទ្រព្យសម្បត្តិ',
                'department_position_order' => 8,
            ],
            [
                'id' => 'tSQMixvqMoh7va2dNBHLttnOkE72',
                'email' => '017222080@admin.com',
                'name' => 'សេង​ ប៉ុណ្ណារា',
                'password' => Hash::make('017222080'),
                'kh_name' => 'សេង​ ប៉ុណ្ណារា',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'នាំក្បួនរថយន្ត',
                'department_position_order' => 6,
            ],
            [
                'id' => 'thJzh0WrpGNJBEZh9L1tkQWNCKE2',
                'email' => '092267399@admin.com',
                'name' => 'សំ ផាន',
                'password' => Hash::make('092267399'),
                'kh_name' => 'សំ ផាន',
                'phone_number' => '092267399',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកជាប់កិច្ចសន្យា',
                'department_position_order' => 27,
            ],
            [
                'id' => 'uU36yDBLVtf8BiLEe7yJ6ReboMq1',
                'email' => '017222080@admin.com',
                'name' => 'test',
                'password' => Hash::make('017222080'),
                'kh_name' => 'test',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'test',
                'department_position_order' => 100,
            ],
            [
                'id' => 'uWNe2rD92aV4REsEDMh4Mb9O6y23',
                'email' => '092373790@admin.com',
                'name' => 'គ្រី ចន្ធីរិទ្ធ',
                'password' => Hash::make('092373790'),
                'kh_name' => 'គ្រី ចន្ធីរិទ្ធ',
                'phone_number' => '092373790',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'បុគ្គលិកបញ្ជូនសារ',
                'department_position_order' => 13,
            ],
            [
                'id' => 'ur1FVZOF0kQTNB5vhOg9uwQbPOm1',
                'email' => '0977207266@admin.com',
                'name' => 'ជាម ចាន់ថន',
                'password' => Hash::make('0977207266'),
                'kh_name' => 'ជាម ចាន់ថន',
                'phone_number' => '0977207266',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'ប្រធានការិយាល័យរដ្ឋបាល',
                'department_position_order' => 3,
            ],
            [
                'id' => 'vTebj6kEqxc8jexNDrB8lj4FEbU2',
                'email' => '012938958@admin.com',
                'name' => 'ម៉ែ បូរីកា',
                'password' => Hash::make('012938958'),
                'kh_name' => 'ម៉ែ បូរីកា',
                'phone_number' => '012938958',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'នាយករង នាយកដ្ឋានគ្រប់គ្រងគ្រោះមហន្តរាយ',
                'department_position_order' => 2,
            ],
            [
                'id' => 'wF1tDygGhnZxQCSTuxbsLMDuMFC2',
                'email' => '017222080@admin.com',
                'name' => 'ជួប សណ្ដាន',
                'password' => Hash::make('017222080'),
                'kh_name' => 'ជួប សណ្ដាន',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'បេីកបរ',
                'department_position_order' => 22,
            ],
            [
                'id' => 'wQeyXTfPXEP6qjb3PkhBPRvKlSP2',
                'email' => '017222082@admin.com',
                'name' => 'មុំ ចន្ធី',
                'password' => Hash::make('017222082'),
                'kh_name' => 'មុំ ចន្ធី',
                'phone_number' => '017222082',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 4,
                'position' => 'នាយិការង នាយកដ្ឋានសុខភាព',
                'department_position_order' => 2,
            ],
            [
                'id' => 'wUasNj1OziVHgGlwWWtJNeMINhu2',
                'email' => '0978886607@admin.com',
                'name' => 'ម៉ៅ ផល្លី',
                'password' => Hash::make('0978886607'),
                'kh_name' => 'ម៉ៅ ផល្លី',
                'phone_number' => '0978886607',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 2,
                'position' => 'មន្រ្តីចុះបញ្ញីទ្រព្យសម្បត្តិ',
                'department_position_order' => 8,
            ],
            [
                'id' => 'xFYcOmF0GrQXWkvC78ZRxsac1W03',
                'email' => '012963966@admin.com',
                'name' => 'អ៊ិត ឬទ្ធី',
                'password' => Hash::make('012963966'),
                'kh_name' => 'អ៊ិត ឬទ្ធី',
                'phone_number' => '012963966',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'អ្នកបើកបររថយន្ត',
                'department_position_order' => 9,
            ],
            [
                'id' => 'xMY2OqjlUvgVzMrDO9sMnUdKRLq1',
                'email' => 'ឲ១៧ ៩៥ ៧៥ ២៣@admin.com',
                'name' => 'ឃឹម ហ៊ាង',
                'password' => Hash::make('ឲ១៧ ៩៥ ៧៥ ២៣'),
                'kh_name' => 'ឃឹម ហ៊ាង',
                'phone_number' => 'ឲ១៧ ៩៥ ៧៥ ២៣',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'បុគ្គលិកបើកបរ',
                'department_position_order' => 10,
            ],
            [
                'id' => 'yg9h0MiHTuX5ojXrL96gqzNGn3x2',
                'email' => '012484270@admin.com',
                'name' => 'ម៉ៅ ថាត',
                'password' => Hash::make('012484270'),
                'kh_name' => 'ម៉ៅ ថាត',
                'phone_number' => '012484270',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'សន្តិសុខ',
                'department_position_order' => 14,
            ],
            [
                'id' => 'yvpGZ3b5TdSQFe2KcGOJU0dF2VG3',
                'email' => '012787657@admin.com',
                'name' => 'យិន​ ប៊ុនសុភក្រ្តា',
                'password' => Hash::make('012787657'),
                'kh_name' => 'យិន​ ប៊ុនសុភក្រ្តា',
                'phone_number' => '012787657',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 3,
                'position' => 'ប្រធានការិយាល័យត្រៀមបង្ការ',
                'department_position_order' => 3,
            ],
            [
                'id' => 'zHwHPl6cRFWVRN3I3UVJagtgpwA3',
                'email' => '081623950@admin.com',
                'name' => 'វ៉ា​ សត្យា',
                'password' => Hash::make('081623950'),
                'kh_name' => 'វ៉ា​ សត្យា',
                'phone_number' => '081623950',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 6,
                'position' => 'មន្ត្រីគ្រប់គ្រងទិន្នួន័យ​ និរដ្ឋបាល',
                'department_position_order' => 4,
            ],
            [
                'id' => 'zSdTTg2HDzULDPVBWm2LvK8720C3',
                'email' => '017222080@admin.com',
                'name' => 'test',
                'password' => Hash::make('017222080'),
                'kh_name' => 'test',
                'phone_number' => '017222080',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'admin',
                'department_position_order' => 100,
            ],
            [
                'id' => 'ze6Vmc0SUoh09N3XEywYAE8RH562',
                'email' => '012798064@admin.com',
                'name' => 'សោម សេរីវឌ្ឍន៍',
                'password' => Hash::make('012798064'),
                'kh_name' => 'សោម សេរីវឌ្ឍន៍',
                'phone_number' => '012798064',
                'user_level_id' => 1,
                'branch_id' => 0,
                'profile_img' => 'https://github.com/shadcn.png',
                'department_id' => 100,
                'position' => 'ជំនួយការអគ្គលេខាធិការដ្ឋាន',
                'department_position_order' => 6,
            ]
        ];

        foreach ($users as $user) {
            $user_created = User::create($user);
            $user_created->assignRole($role);
        }
    }
}
