<?php

namespace Database\Seeders;

use App\Models\SubBranch;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubBranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        SubBranch::insert([
            [
                "id" => 102,
                "kh_name" => "មង្គលបូរី",
                "en_name" => "Mongkol Borei",
                "branch_id" => 1,
                "district_id" => 102,
            ],
            [
                "id" => 103,
                "kh_name" => "ភ្នំស្រុក",
                "en_name" => "Phnum Srok",
                "branch_id" => 1,
                "district_id" => 103,
            ],
            [
                "id" => 104,
                "kh_name" => "ព្រះនេត្រព្រះ",
                "en_name" => "Preah Netr Preah",
                "branch_id" => 1,
                "district_id" => 104,
            ],
            [
                "id" => 105,
                "kh_name" => "អូរជ្រៅ",
                "en_name" => "Ou Chrov",
                "branch_id" => 1,
                "district_id" => 105,
            ],
            [
                "id" => 106,
                "kh_name" => "សិរីសោភ័ណ",
                "en_name" => "Serei Saophoan",
                "branch_id" => 1,
                "district_id" => 106,
            ],
            [
                "id" => 107,
                "kh_name" => "ថ្មពួក",
                "en_name" => "Thma Puok",
                "branch_id" => 1,
                "district_id" => 107,
            ],
            [
                "id" => 108,
                "kh_name" => "ស្វាយចេក",
                "en_name" => "Svay Chek",
                "branch_id" => 1,
                "district_id" => 108,
            ],
            [
                "id" => 109,
                "kh_name" => "ម៉ាឡៃ",
                "en_name" => "Malai",
                "branch_id" => 1,
                "district_id" => 109,
            ],
            [
                "id" => 110,
                "kh_name" => "ប៉ោយប៉ែត",
                "en_name" => "Paoy Paet",
                "branch_id" => 1,
                "district_id" => 110,
            ],
            [
                "id" => 201,
                "kh_name" => "បាណន់",
                "en_name" => "Banan",
                "branch_id" => 2,
                "district_id" => 201,
            ],
            [
                "id" => 202,
                "kh_name" => "ថ្មគោល",
                "en_name" => "Thma Koul",
                "branch_id" => 2,
                "district_id" => 202,
            ],
            [
                "id" => 203,
                "kh_name" => "បាត់ដំបង",
                "en_name" => "Battambang",
                "branch_id" => 2,
                "district_id" => 203,
            ],
            [
                "id" => 204,
                "kh_name" => "បវេល",
                "en_name" => "Bavel",
                "branch_id" => 2,
                "district_id" => 204,
            ],
            [
                "id" => 205,
                "kh_name" => "ឯកភ្នំ",
                "en_name" => "Aek Phnum",
                "branch_id" => 2,
                "district_id" => 205,
            ],
            [
                "id" => 206,
                "kh_name" => "មោងឫស្សី",
                "en_name" => "Moung Ruessei",
                "branch_id" => 2,
                "district_id" => 206,
            ],
            [
                "id" => 207,
                "kh_name" => "រតនមណ្ឌល",
                "en_name" => "Rotonak Mondol",
                "branch_id" => 2,
                "district_id" => 207,
            ],
            [
                "id" => 208,
                "kh_name" => "សង្កែ",
                "en_name" => "Sangkae",
                "branch_id" => 2,
                "district_id" => 208,
            ],
            [
                "id" => 209,
                "kh_name" => "សំឡូត",
                "en_name" => "Samlout",
                "branch_id" => 2,
                "district_id" => 209,
            ],
            [
                "id" => 210,
                "kh_name" => "សំពៅលូន",
                "en_name" => "Sampov Lun",
                "branch_id" => 2,
                "district_id" => 210,
            ],
            [
                "id" => 211,
                "kh_name" => "ភ្នំព្រឹក",
                "en_name" => "Phnum Proek",
                "branch_id" => 2,
                "district_id" => 211,
            ],
            [
                "id" => 212,
                "kh_name" => "កំរៀង",
                "en_name" => "Kamrieng",
                "branch_id" => 2,
                "district_id" => 212,
            ],
            [
                "id" => 213,
                "kh_name" => "គាស់ក្រឡ",
                "en_name" => "Koas Krala",
                "branch_id" => 2,
                "district_id" => 213,
            ],
            [
                "id" => 214,
                "kh_name" => "រុក្ខគិរី",
                "en_name" => "Rukh Kiri",
                "branch_id" => 2,
                "district_id" => 214,
            ],
            [
                "id" => 301,
                "kh_name" => "បាធាយ",
                "en_name" => "Batheay",
                "branch_id" => 3,
                "district_id" => 301,
            ],
            [
                "id" => 302,
                "kh_name" => "ចំការលើ",
                "en_name" => "Chamkar Leu",
                "branch_id" => 3,
                "district_id" => 302,
            ],
            [
                "id" => 303,
                "kh_name" => "ជើងព្រៃ",
                "en_name" => "Cheung Prey",
                "branch_id" => 3,
                "district_id" => 303,
            ],
            [
                "id" => 305,
                "kh_name" => "កំពង់ចាម",
                "en_name" => "Kampong Cham",
                "branch_id" => 3,
                "district_id" => 305,
            ],
            [
                "id" => 306,
                "kh_name" => "កំពង់សៀម",
                "en_name" => "Kampong Siem",
                "branch_id" => 3,
                "district_id" => 306,
            ],
            [
                "id" => 307,
                "kh_name" => "កងមាស",
                "en_name" => "Kang Meas",
                "branch_id" => 3,
                "district_id" => 307,
            ],
            [
                "id" => 308,
                "kh_name" => "កោះសូទិន",
                "en_name" => "Kaoh Soutin",
                "branch_id" => 3,
                "district_id" => 308,
            ],
            [
                "id" => 313,
                "kh_name" => "ព្រៃឈរ",
                "en_name" => "Prey Chhor",
                "branch_id" => 3,
                "district_id" => 313,
            ],
            [
                "id" => 314,
                "kh_name" => "ស្រីសន្ធរ",
                "en_name" => "Srei Santhor",
                "branch_id" => 3,
                "district_id" => 314,
            ],
            [
                "id" => 315,
                "kh_name" => "ស្ទឹងត្រង់",
                "en_name" => "Stueng Trang",
                "branch_id" => 3,
                "district_id" => 315,
            ],
            [
                "id" => 401,
                "kh_name" => "បរិបូណ៌",
                "en_name" => "Baribour",
                "branch_id" => 4,
                "district_id" => 401,
            ],
            [
                "id" => 402,
                "kh_name" => "ជលគីរី",
                "en_name" => "Chol Kiri",
                "branch_id" => 4,
                "district_id" => 402,
            ],
            [
                "id" => 403,
                "kh_name" => "កំពង់ឆ្នាំង",
                "en_name" => "Kampong Chhnang",
                "branch_id" => 4,
                "district_id" => 403,
            ],
            [
                "id" => 404,
                "kh_name" => "កំពង់លែង",
                "en_name" => "Kampong Leaeng",
                "branch_id" => 4,
                "district_id" => 404,
            ],
            [
                "id" => 405,
                "kh_name" => "កំពង់ត្រឡាច",
                "en_name" => "Kampong Tralach",
                "branch_id" => 4,
                "district_id" => 405,
            ],
            [
                "id" => 406,
                "kh_name" => "រលាប្អៀរ",
                "en_name" => "Rolea Bier",
                "branch_id" => 4,
                "district_id" => 406,
            ],
            [
                "id" => 407,
                "kh_name" => "សាមគ្គីមានជ័យ",
                "en_name" => "Sameakki Mean Chey",
                "branch_id" => 4,
                "district_id" => 407,
            ],
            [
                "id" => 408,
                "kh_name" => "ទឹកផុស",
                "en_name" => "Tuek Phos",
                "branch_id" => 4,
                "district_id" => 408,
            ],
            [
                "id" => 501,
                "kh_name" => "បរសេដ្ឋ",
                "en_name" => "Basedth",
                "branch_id" => 5,
                "district_id" => 501,
            ],
            [
                "id" => 502,
                "kh_name" => "ច្បារមន",
                "en_name" => "Chbar Mon",
                "branch_id" => 5,
                "district_id" => 502,
            ],
            [
                "id" => 503,
                "kh_name" => "គងពិសី",
                "en_name" => "Kong Pisei",
                "branch_id" => 5,
                "district_id" => 503,
            ],
            [
                "id" => 504,
                "kh_name" => "ឱរ៉ាល់",
                "en_name" => "Aoral",
                "branch_id" => 5,
                "district_id" => 504,
            ],
            [
                "id" => 505,
                "kh_name" => "ឧដុង្គ",
                "en_name" => "Odongk",
                "branch_id" => 5,
                "district_id" => 505,
            ],
            [
                "id" => 506,
                "kh_name" => "ភ្នំស្រួច",
                "en_name" => "Phnum Sruoch",
                "branch_id" => 5,
                "district_id" => 506,
            ],
            [
                "id" => 507,
                "kh_name" => "សំរោងទង",
                "en_name" => "Samraong Tong",
                "branch_id" => 5,
                "district_id" => 507,
            ],
            [
                "id" => 508,
                "kh_name" => "ថ្ពង",
                "en_name" => "Thpong",
                "branch_id" => 5,
                "district_id" => 508,
            ],
            [
                "id" => 601,
                "kh_name" => "បារាយណ៍",
                "en_name" => "Baray",
                "branch_id" => 6,
                "district_id" => 601,
            ],
            [
                "id" => 602,
                "kh_name" => "កំពង់ស្វាយ",
                "en_name" => "Kampong Svay",
                "branch_id" => 6,
                "district_id" => 602,
            ],
            [
                "id" => 603,
                "kh_name" => "ស្ទឹងសែន",
                "en_name" => "Stueng Saen",
                "branch_id" => 6,
                "district_id" => 603,
            ],
            [
                "id" => 604,
                "kh_name" => "ប្រាសាទបល្ល័ង្គ",
                "en_name" => "Prasat Ballangk",
                "branch_id" => 6,
                "district_id" => 604,
            ],
            [
                "id" => 605,
                "kh_name" => "ប្រាសាទសំបូរ",
                "en_name" => "Prasat Sambour",
                "branch_id" => 6,
                "district_id" => 605,
            ],
            [
                "id" => 606,
                "kh_name" => "សន្តាន់",
                "en_name" => "Sandan",
                "branch_id" => 6,
                "district_id" => 606,
            ],
            [
                "id" => 607,
                "kh_name" => "សន្ទុក",
                "en_name" => "Santuk",
                "branch_id" => 6,
                "district_id" => 607,
            ],
            [
                "id" => 608,
                "kh_name" => "ស្ទោង",
                "en_name" => "Stoung",
                "branch_id" => 6,
                "district_id" => 608,
            ],
            [
                "id" => 609,
                "kh_name" => "តាំងគោក",
                "en_name" => "Taing Kouk",
                "branch_id" => 6,
                "district_id" => 609,
            ],
            [
                "id" => 701,
                "kh_name" => "អង្គរជ័យ",
                "en_name" => "Angkor Chey",
                "branch_id" => 7,
                "district_id" => 701,
            ],
            [
                "id" => 702,
                "kh_name" => "បន្ទាយមាស",
                "en_name" => "Banteay Meas",
                "branch_id" => 7,
                "district_id" => 702,
            ],
            [
                "id" => 703,
                "kh_name" => "ឈូក",
                "en_name" => "Chhuk",
                "branch_id" => 7,
                "district_id" => 703,
            ],
            [
                "id" => 704,
                "kh_name" => "ជុំគិរី",
                "en_name" => "Chum Kiri",
                "branch_id" => 7,
                "district_id" => 704,
            ],
            [
                "id" => 705,
                "kh_name" => "ដងទង់",
                "en_name" => "Dang Tong",
                "branch_id" => 7,
                "district_id" => 705,
            ],
            [
                "id" => 706,
                "kh_name" => "កំពង់ត្រាច",
                "en_name" => "Kampong Trach",
                "branch_id" => 7,
                "district_id" => 706,
            ],
            [
                "id" => 707,
                "kh_name" => "ទឹកឈូ",
                "en_name" => "Tuek Chhou",
                "branch_id" => 7,
                "district_id" => 707,
            ],
            [
                "id" => 708,
                "kh_name" => "កំពត",
                "en_name" => "Kampot",
                "branch_id" => 7,
                "district_id" => 708,
            ],
            [
                "id" => 801,
                "kh_name" => "កណ្ដាលស្ទឹង",
                "en_name" => "Kandal Stueng",
                "branch_id" => 8,
                "district_id" => 801,
            ],
            [
                "id" => 802,
                "kh_name" => "កៀនស្វាយ",
                "en_name" => "Kien Svay",
                "branch_id" => 8,
                "district_id" => 802,
            ],
            [
                "id" => 803,
                "kh_name" => "ខ្សាច់កណ្ដាល",
                "en_name" => "Khsach Kandal",
                "branch_id" => 8,
                "district_id" => 803,
            ],
            [
                "id" => 804,
                "kh_name" => "កោះធំ",
                "en_name" => "Kaoh Thum",
                "branch_id" => 8,
                "district_id" => 804,
            ],
            [
                "id" => 805,
                "kh_name" => "លើកដែក",
                "en_name" => "Leuk Daek",
                "branch_id" => 8,
                "district_id" => 805,
            ],
            [
                "id" => 806,
                "kh_name" => "ល្វាឯម",
                "en_name" => "Lvea Aem",
                "branch_id" => 8,
                "district_id" => 806,
            ],
            [
                "id" => 807,
                "kh_name" => "មុខកំពូល",
                "en_name" => "Mukh Kampul",
                "branch_id" => 8,
                "district_id" => 807,
            ],
            [
                "id" => 808,
                "kh_name" => "អង្គស្នួល",
                "en_name" => "Angk Snuol",
                "branch_id" => 8,
                "district_id" => 808,
            ],
            [
                "id" => 809,
                "kh_name" => "ពញាឮ",
                "en_name" => "Ponhea Lueu",
                "branch_id" => 8,
                "district_id" => 809,
            ],
            [
                "id" => 810,
                "kh_name" => "ស្អាង",
                "en_name" => "Sang",
                "branch_id" => 8,
                "district_id" => 810,
            ],
            [
                "id" => 811,
                "kh_name" => "តាខ្មៅ",
                "en_name" => "Ta Khmau",
                "branch_id" => 8,
                "district_id" => 811,
            ],
            [
                "id" => 901,
                "kh_name" => "បុទុមសាគរ",
                "en_name" => "Botum Sakor",
                "branch_id" => 9,
                "district_id" => 901,
            ],
            [
                "id" => 902,
                "kh_name" => "គិរីសាគរ",
                "en_name" => "Kiri Sakor",
                "branch_id" => 9,
                "district_id" => 902,
            ],
            [
                "id" => 903,
                "kh_name" => "កោះកុង",
                "en_name" => "Kaoh Kong",
                "branch_id" => 9,
                "district_id" => 903,
            ],
            [
                "id" => 904,
                "kh_name" => "ខេមរភូមិន្ទ",
                "en_name" => "Khemara Phoumin",
                "branch_id" => 9,
                "district_id" => 904,
            ],
            [
                "id" => 905,
                "kh_name" => "មណ្ឌលសីមា",
                "en_name" => "Mondol Seima",
                "branch_id" => 9,
                "district_id" => 905,
            ],
            [
                "id" => 906,
                "kh_name" => "ស្រែ អំបិល",
                "en_name" => "Srae Ambel",
                "branch_id" => 9,
                "district_id" => 906,
            ],
            [
                "id" => 907,
                "kh_name" => "ថ្មបាំង",
                "en_name" => "Thma Bang",
                "branch_id" => 9,
                "district_id" => 907,
            ],
            [
                "id" => 1001,
                "kh_name" => "ឆ្លូង",
                "en_name" => "Chhloung",
                "branch_id" => 10,
                "district_id" => 1001,
            ],
            [
                "id" => 1002,
                "kh_name" => "ក្រចេះ",
                "en_name" => "Kracheh",
                "branch_id" => 10,
                "district_id" => 1002,
            ],
            [
                "id" => 1003,
                "kh_name" => "ព្រែកប្រសព្វ",
                "en_name" => "Prek Prasab",
                "branch_id" => 10,
                "district_id" => 1003,
            ],
            [
                "id" => 1004,
                "kh_name" => "សំបូរ",
                "en_name" => "Sambour",
                "branch_id" => 10,
                "district_id" => 1004,
            ],
            [
                "id" => 1005,
                "kh_name" => "ស្នួល",
                "en_name" => "Snuol",
                "branch_id" => 10,
                "district_id" => 1005,
            ],
            [
                "id" => 1006,
                "kh_name" => "ចិត្របុរី",
                "en_name" => "Chetr Borei",
                "branch_id" => 10,
                "district_id" => 1006,
            ],
            [
                "id" => 1101,
                "kh_name" => "កែវសីមា",
                "en_name" => "Kaev Seima",
                "branch_id" => 11,
                "district_id" => 1101,
            ],
            [
                "id" => 1102,
                "kh_name" => "កោះញែក",
                "en_name" => "Kaoh Nheaek",
                "branch_id" => 11,
                "district_id" => 1102,
            ],
            [
                "id" => 1103,
                "kh_name" => "អូររាំង",
                "en_name" => "Ou Reang",
                "branch_id" => 11,
                "district_id" => 1103,
            ],
            [
                "id" => 1104,
                "kh_name" => "ពេជ្រាដា",
                "en_name" => "Pech Chreada",
                "branch_id" => 11,
                "district_id" => 1104,
            ],
            [
                "id" => 1105,
                "kh_name" => "សែនមនោរម្យ",
                "en_name" => "Saen Monourom",
                "branch_id" => 11,
                "district_id" => 1105,
            ],
            [
                "id" => 1201,
                "kh_name" => "ចំការមន",
                "en_name" => "Chamkar Mon",
                "branch_id" => 12,
                "district_id" => 1201,
            ],
            [
                "id" => 1202,
                "kh_name" => "ដូនពេញ",
                "en_name" => "Doun Penh",
                "branch_id" => 12,
                "district_id" => 1202,
            ],
            [
                "id" => 1203,
                "kh_name" => "៧មករា",
                "en_name" => "Prampir Meakkakra",
                "branch_id" => 12,
                "district_id" => 1203,
            ],
            [
                "id" => 1204,
                "kh_name" => "ទួលគោក",
                "en_name" => "Tuol Kouk",
                "branch_id" => 12,
                "district_id" => 1204,
            ],
            [
                "id" => 1205,
                "kh_name" => "ដង្កោ",
                "en_name" => "Dangkao",
                "branch_id" => 12,
                "district_id" => 1205,
            ],
            [
                "id" => 1206,
                "kh_name" => "មានជ័យ",
                "en_name" => "Mean Chey",
                "branch_id" => 12,
                "district_id" => 1206,
            ],
            [
                "id" => 1207,
                "kh_name" => "ឫស្សីកែវ",
                "en_name" => "Russey Keo",
                "branch_id" => 12,
                "district_id" => 1207,
            ],
            [
                "id" => 1208,
                "kh_name" => "សែនសុខ",
                "en_name" => "Saensokh",
                "branch_id" => 12,
                "district_id" => 1208,
            ],
            [
                "id" => 1209,
                "kh_name" => "ពោធិ៍សែនជ័យ",
                "en_name" => "Pur SenChey",
                "branch_id" => 12,
                "district_id" => 1209,
            ],
            [
                "id" => 1210,
                "kh_name" => "ជ្រោយចង្វារ",
                "en_name" => "Chraoy Chongvar",
                "branch_id" => 12,
                "district_id" => 1210,
            ],
            [
                "id" => 1211,
                "kh_name" => "ព្រែកព្នៅ",
                "en_name" => "Praek Pnov",
                "branch_id" => 12,
                "district_id" => 1211,
            ],
            [
                "id" => 1212,
                "kh_name" => "ច្បារអំពៅ",
                "en_name" => "Chbar Ampov",
                "branch_id" => 12,
                "district_id" => 1212,
            ],
            [
                "id" => 1213,
                "kh_name" => "បឹងកេងកង",
                "en_name" => "Kengkong",
                "branch_id" => 12,
                "district_id" => 1213,
            ],
            [
                "id" => 1214,
                "kh_name" => "កំបូល",
                "en_name" => "Kambol",
                "branch_id" => 12,
                "district_id" => 1214,
            ],
            [
                "id" => 1301,
                "kh_name" => "ជ័យសែន",
                "en_name" => "Chey Saen",
                "branch_id" => 13,
                "district_id" => 1301,
            ],
            [
                "id" => 1302,
                "kh_name" => "ឆែប",
                "en_name" => "Chhaeb",
                "branch_id" => 13,
                "district_id" => 1302,
            ],
            [
                "id" => 1303,
                "kh_name" => "ជាំក្សាន្ដ",
                "en_name" => "Choam Ksant",
                "branch_id" => 13,
                "district_id" => 1303,
            ],
            [
                "id" => 1304,
                "kh_name" => "គូលែន",
                "en_name" => "Kuleaen",
                "branch_id" => 13,
                "district_id" => 1304,
            ],
            [
                "id" => 1305,
                "kh_name" => "រវៀង",
                "en_name" => "Rovieng",
                "branch_id" => 13,
                "district_id" => 1305,
            ],
            [
                "id" => 1306,
                "kh_name" => "សង្គមថ្មី",
                "en_name" => "Sangkum Thmei",
                "branch_id" => 13,
                "district_id" => 1306,
            ],
            [
                "id" => 1307,
                "kh_name" => "ត្បែងមានជ័យ",
                "en_name" => "Tbaeng Mean Chey",
                "branch_id" => 13,
                "district_id" => 1307,
            ],
            [
                "id" => 1308,
                "kh_name" => "ព្រះវិហារ",
                "en_name" => "Preah Vihear",
                "branch_id" => 13,
                "district_id" => 1308,
            ],
            [
                "id" => 1401,
                "kh_name" => "បាភ្នំ",
                "en_name" => "Ba Phnum",
                "branch_id" => 14,
                "district_id" => 1401,
            ],
            [
                "id" => 1402,
                "kh_name" => "កំចាយមារ",
                "en_name" => "Kamchay Mear",
                "branch_id" => 14,
                "district_id" => 1402,
            ],
            [
                "id" => 1403,
                "kh_name" => "កំពង់ត្របែក",
                "en_name" => "Kampong Trabaek",
                "branch_id" => 14,
                "district_id" => 1403,
            ],
            [
                "id" => 1404,
                "kh_name" => "កញ្ជ្រៀច",
                "en_name" => "Kanhchriech",
                "branch_id" => 14,
                "district_id" => 1404,
            ],
            [
                "id" => 1405,
                "kh_name" => "មេសាង",
                "en_name" => "Me Sang",
                "branch_id" => 14,
                "district_id" => 1405,
            ],
            [
                "id" => 1406,
                "kh_name" => "ពាមជរ",
                "en_name" => "Peam Chor",
                "branch_id" => 14,
                "district_id" => 1406,
            ],
            [
                "id" => 1407,
                "kh_name" => "ពាមរក៍",
                "en_name" => "Peam Ro",
                "branch_id" => 14,
                "district_id" => 1407,
            ],
            [
                "id" => 1408,
                "kh_name" => "ពារាំង",
                "en_name" => "Pea Reang",
                "branch_id" => 14,
                "district_id" => 1408,
            ],
            [
                "id" => 1409,
                "kh_name" => "ព្រះស្ដេច",
                "en_name" => "Preah Sdach",
                "branch_id" => 14,
                "district_id" => 1409,
            ],
            [
                "id" => 1410,
                "kh_name" => "ព្រៃវែង",
                "en_name" => "Prey Veng",
                "branch_id" => 14,
                "district_id" => 1410,
            ],
            [
                "id" => 1411,
                "kh_name" => "ពោធិ៍រៀង",
                "en_name" => "Pur Rieng",
                "branch_id" => 14,
                "district_id" => 1411,
            ],
            [
                "id" => 1412,
                "kh_name" => "ស៊ីធរកណ្ដាល",
                "en_name" => "Sithor Kandal",
                "branch_id" => 14,
                "district_id" => 1412,
            ],
            [
                "id" => 1413,
                "kh_name" => "ស្វាយអន្ទរ",
                "en_name" => "Svay Antor",
                "branch_id" => 14,
                "district_id" => 1413,
            ],
            [
                "id" => 1501,
                "kh_name" => "បាកាន",
                "en_name" => "Bakan",
                "branch_id" => 15,
                "district_id" => 1501,
            ],
            [
                "id" => 1502,
                "kh_name" => "កណ្ដៀង",
                "en_name" => "Kandieng",
                "branch_id" => 15,
                "district_id" => 1502,
            ],
            [
                "id" => 1503,
                "kh_name" => "ក្រគរ",
                "en_name" => "Krakor",
                "branch_id" => 15,
                "district_id" => 1503,
            ],
            [
                "id" => 1504,
                "kh_name" => "ភ្នំក្រវ៉ាញ",
                "en_name" => "Phnum Kravanh",
                "branch_id" => 15,
                "district_id" => 1504,
            ],
            [
                "id" => 1505,
                "kh_name" => "ពោធិ៍សាត់",
                "en_name" => "Pursat",
                "branch_id" => 15,
                "district_id" => 1505,
            ],
            [
                "id" => 1506,
                "kh_name" => "វាលវែង",
                "en_name" => "Veal Veaeng",
                "branch_id" => 15,
                "district_id" => 1506,
            ],
            [
                "id" => 1507,
                "kh_name" => "តាលោសែនជ័យ",
                "en_name" => "Ta Lou Senchey",
                "branch_id" => 15,
                "district_id" => 1507,
            ],
            [
                "id" => 1601,
                "kh_name" => "អណ្ដូងមាស",
                "en_name" => "Andoung Meas",
                "branch_id" => 16,
                "district_id" => 1601,
            ],
            [
                "id" => 1602,
                "kh_name" => "បានលុង",
                "en_name" => "Ban Lung",
                "branch_id" => 16,
                "district_id" => 1602,
            ],
            [
                "id" => 1603,
                "kh_name" => "បរកែវ",
                "en_name" => "Bar Kaev",
                "branch_id" => 16,
                "district_id" => 1603,
            ],
            [
                "id" => 1604,
                "kh_name" => "កូនមុំ",
                "en_name" => "Koun Mom",
                "branch_id" => 16,
                "district_id" => 1604,
            ],
            [
                "id" => 1605,
                "kh_name" => "លំផាត់",
                "en_name" => "Lumphat",
                "branch_id" => 16,
                "district_id" => 1605,
            ],
            [
                "id" => 1606,
                "kh_name" => "អូរជុំ",
                "en_name" => "Ou Chum",
                "branch_id" => 16,
                "district_id" => 1606,
            ],
            [
                "id" => 1607,
                "kh_name" => "អូរយ៉ាដាវ",
                "en_name" => "Ou Ya Dav",
                "branch_id" => 16,
                "district_id" => 1607,
            ],
            [
                "id" => 1608,
                "kh_name" => "តាវែង",
                "en_name" => "Ta Veaeng",
                "branch_id" => 16,
                "district_id" => 1608,
            ],
            [
                "id" => 1609,
                "kh_name" => "វើនសៃ",
                "en_name" => "Veun Sai",
                "branch_id" => 16,
                "district_id" => 1609,
            ],
            [
                "id" => 1701,
                "kh_name" => "អង្គរជុំ",
                "en_name" => "Angkor Chum",
                "branch_id" => 17,
                "district_id" => 1701,
            ],
            [
                "id" => 1702,
                "kh_name" => "អង្គរធំ",
                "en_name" => "Angkor Thum",
                "branch_id" => 17,
                "district_id" => 1702,
            ],
            [
                "id" => 1703,
                "kh_name" => "បន្ទាយស្រី",
                "en_name" => "Banteay Srei",
                "branch_id" => 17,
                "district_id" => 1703,
            ],
            [
                "id" => 1704,
                "kh_name" => "ជីក្រែង",
                "en_name" => "Chi Kraeng",
                "branch_id" => 17,
                "district_id" => 1704,
            ],
            [
                "id" => 1706,
                "kh_name" => "ក្រឡាញ់",
                "en_name" => "Kralanh",
                "branch_id" => 17,
                "district_id" => 1706,
            ],
            [
                "id" => 1707,
                "kh_name" => "ពួក",
                "en_name" => "Puok",
                "branch_id" => 17,
                "district_id" => 1707,
            ],
            [
                "id" => 1709,
                "kh_name" => "ប្រាសាទបាគង",
                "en_name" => "Prasat Bakong",
                "branch_id" => 17,
                "district_id" => 1709,
            ],
            [
                "id" => 1710,
                "kh_name" => "សៀមរាប",
                "en_name" => "Siem Reap",
                "branch_id" => 17,
                "district_id" => 1710,
            ],
            [
                "id" => 1711,
                "kh_name" => "សូទ្រនិគម",
                "en_name" => "Soutr Nikom",
                "branch_id" => 17,
                "district_id" => 1711,
            ],
            [
                "id" => 1712,
                "kh_name" => "ស្រីស្នំ",
                "en_name" => "Srei Snam",
                "branch_id" => 17,
                "district_id" => 1712,
            ],
            [
                "id" => 1713,
                "kh_name" => "ស្វាយលើ",
                "en_name" => "Svay Leu",
                "branch_id" => 17,
                "district_id" => 1713,
            ],
            [
                "id" => 1714,
                "kh_name" => "វ៉ារិន",
                "en_name" => "Varin",
                "branch_id" => 17,
                "district_id" => 1714,
            ],
            [
                "id" => 1801,
                "kh_name" => "ព្រះសីហនុ",
                "en_name" => "Preah Sihanouk",
                "branch_id" => 18,
                "district_id" => 1801,
            ],
            [
                "id" => 1802,
                "kh_name" => "ព្រៃនប់",
                "en_name" => "Prey Nob",
                "branch_id" => 18,
                "district_id" => 1802,
            ],
            [
                "id" => 1803,
                "kh_name" => "ស្ទឹងហាវ",
                "en_name" => "Stueng Hav",
                "branch_id" => 18,
                "district_id" => 1803,
            ],
            [
                "id" => 1804,
                "kh_name" => "កំពង់សីលា",
                "en_name" => "Kampong Seila",
                "branch_id" => 18,
                "district_id" => 1804,
            ],
            [
                "id" => 1805,
                "kh_name" => "កោះរ៉ុង",
                "en_name" => "Kaoh Rung Municipality",
                "branch_id" => 18,
                "district_id" => 1805,
            ],
            [
                "id" => 1901,
                "kh_name" => "សេសាន",
                "en_name" => "Sesan",
                "branch_id" => 19,
                "district_id" => 1901,
            ],
            [
                "id" => 1902,
                "kh_name" => "សៀមបូក",
                "en_name" => "Siem Bouk",
                "branch_id" => 19,
                "district_id" => 1902,
            ],
            [
                "id" => 1903,
                "kh_name" => "សៀមប៉ាង",
                "en_name" => "Siem Pang",
                "branch_id" => 19,
                "district_id" => 1903,
            ],
            [
                "id" => 1904,
                "kh_name" => "ស្ទឹងត្រែង",
                "en_name" => "Stueng Traeng",
                "branch_id" => 19,
                "district_id" => 1904,
            ],
            [
                "id" => 1905,
                "kh_name" => "ថាឡាបរិវ៉ាត់",
                "en_name" => "Thala Barivat",
                "branch_id" => 19,
                "district_id" => 1905,
            ],
            [
                "id" => 1906,
                "kh_name" => "បុរីអូរស្វាយសែនជ័យ",
                "en_name" => "Borei Ou Svay Senchey",
                "branch_id" => 19,
                "district_id" => 1906,
            ],
            [
                "id" => 2001,
                "kh_name" => "ចន្ទ្រា",
                "en_name" => "Chantrea",
                "branch_id" => 20,
                "district_id" => 2001,
            ],
            [
                "id" => 2002,
                "kh_name" => "កំពង់រោទិ៍",
                "en_name" => "Kampong Rou",
                "branch_id" => 20,
                "district_id" => 2002,
            ],
            [
                "id" => 2003,
                "kh_name" => "រំដួល",
                "en_name" => "Rumduol",
                "branch_id" => 20,
                "district_id" => 2003,
            ],
            [
                "id" => 2004,
                "kh_name" => "រមាសហែក",
                "en_name" => "Romeas Haek",
                "branch_id" => 20,
                "district_id" => 2004,
            ],
            [
                "id" => 2005,
                "kh_name" => "ស្វាយជ្រំ",
                "en_name" => "Svay Chrum",
                "branch_id" => 20,
                "district_id" => 2005,
            ],
            [
                "id" => 2006,
                "kh_name" => "ស្វាយរៀង",
                "en_name" => "Svay Rieng",
                "branch_id" => 20,
                "district_id" => 2006,
            ],
            [
                "id" => 2007,
                "kh_name" => "ស្វាយទាប",
                "en_name" => "Svay Teab",
                "branch_id" => 20,
                "district_id" => 2007,
            ],
            [
                "id" => 2008,
                "kh_name" => "បាវិត",
                "en_name" => "Bavet",
                "branch_id" => 20,
                "district_id" => 2008,
            ],
            [
                "id" => 2101,
                "kh_name" => "អង្គរបូរី",
                "en_name" => "Angkor Borei",
                "branch_id" => 21,
                "district_id" => 2101,
            ],
            [
                "id" => 2102,
                "kh_name" => "បាទី",
                "en_name" => "Bati",
                "branch_id" => 21,
                "district_id" => 2102,
            ],
            [
                "id" => 2103,
                "kh_name" => "បូរីជលសារ",
                "en_name" => "Borei Cholsar",
                "branch_id" => 21,
                "district_id" => 2103,
            ],
            [
                "id" => 2104,
                "kh_name" => "គីរីវង់",
                "en_name" => "Kiri Vong",
                "branch_id" => 21,
                "district_id" => 2104,
            ],
            [
                "id" => 2105,
                "kh_name" => "កោះអណ្ដែត",
                "en_name" => "Kaoh Andaet",
                "branch_id" => 21,
                "district_id" => 2105,
            ],
            [
                "id" => 2106,
                "kh_name" => "ព្រៃកប្បាស",
                "en_name" => "Prey Kabbas",
                "branch_id" => 21,
                "district_id" => 2106,
            ],
            [
                "id" => 2107,
                "kh_name" => "សំរោង",
                "en_name" => "Samraong",
                "branch_id" => 21,
                "district_id" => 2107,
            ],
            [
                "id" => 2108,
                "kh_name" => "ដូនកែវ",
                "en_name" => "Doun Kaev",
                "branch_id" => 21,
                "district_id" => 2108,
            ],
            [
                "id" => 2109,
                "kh_name" => "ត្រាំកក់",
                "en_name" => "Tram Kak",
                "branch_id" => 21,
                "district_id" => 2109,
            ],
            [
                "id" => 2110,
                "kh_name" => "ទ្រាំង",
                "en_name" => "Treang",
                "branch_id" => 21,
                "district_id" => 2110,
            ],
            [
                "id" => 2201,
                "kh_name" => "អន្លង់វែង",
                "en_name" => "Anlong Veaeng",
                "branch_id" => 22,
                "district_id" => 2201,
            ],
            [
                "id" => 2202,
                "kh_name" => "បន្ទាយអំពិល",
                "en_name" => "Banteay Ampil",
                "branch_id" => 22,
                "district_id" => 2202,
            ],
            [
                "id" => 2203,
                "kh_name" => "ចុងកាល់",
                "en_name" => "Chong Kal",
                "branch_id" => 22,
                "district_id" => 2203,
            ],
            [
                "id" => 2204,
                "kh_name" => "សំរោង",
                "en_name" => "Samraong",
                "branch_id" => 22,
                "district_id" => 2204,
            ],
            [
                "id" => 2205,
                "kh_name" => "ត្រពាំងប្រាសាទ",
                "en_name" => "Trapeang Prasat",
                "branch_id" => 22,
                "district_id" => 2205,
            ],
            [
                "id" => 2301,
                "kh_name" => "ដំណាក់ចង្អើរ",
                "en_name" => "Damnak Changaeur",
                "branch_id" => 23,
                "district_id" => 2301,
            ],
            [
                "id" => 2302,
                "kh_name" => "កែប",
                "en_name" => "Kaeb",
                "branch_id" => 23,
                "district_id" => 2302,
            ],
            [
                "id" => 2401,
                "kh_name" => "ប៉ៃលិន",
                "en_name" => "Pailin",
                "branch_id" => 24,
                "district_id" => 2401,
            ],
            [
                "id" => 2402,
                "kh_name" => "សាលាក្រៅ",
                "en_name" => "Sala Krau",
                "branch_id" => 24,
                "district_id" => 2402,
            ],
            [
                "id" => 2501,
                "kh_name" => "តំបែរ",
                "en_name" => "Dambae",
                "branch_id" => 25,
                "district_id" => 2501,
            ],
            [
                "id" => 2502,
                "kh_name" => "ក្រូចឆ្មារ",
                "en_name" => "Krouch Chhmar",
                "branch_id" => 25,
                "district_id" => 2502,
            ],
            [
                "id" => 2503,
                "kh_name" => "មេមត់",
                "en_name" => "Memot",
                "branch_id" => 25,
                "district_id" => 2503,
            ],
            [
                "id" => 2504,
                "kh_name" => "អូររាំងឪ",
                "en_name" => "Ou Reang Ov",
                "branch_id" => 25,
                "district_id" => 2504,
            ],
            [
                "id" => 2505,
                "kh_name" => "ពញាក្រែក",
                "en_name" => "Ponhea Kraek",
                "branch_id" => 25,
                "district_id" => 2505,
            ],
            [
                "id" => 2506,
                "kh_name" => "សួង",
                "en_name" => "Suong",
                "branch_id" => 25,
                "district_id" => 2506,
            ],
            [
                "id" => 2507,
                "kh_name" => "ត្បូងឃ្មុំ",
                "en_name" => "Tboung Khmum",
                "branch_id" => 25,
                "district_id" => 2507,
            ],
        ]);
    }
}
